/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA;
typedef struct tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA;
typedef struct tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ;
typedef struct tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ;
typedef struct tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ;
typedef struct tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg;
typedef struct tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w;
typedef struct tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng;
typedef NIM_CHAR tyArray__x9aRkN8DVcTBDUl3hEPJutg[32];
struct tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA {
	char dummy;
};
typedef N_CDECL_PTR(void, tyProc__AL9bRLkzEO68chD0gurqcTA) (tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* a0_p0);
struct tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ {
	tyProc__AL9bRLkzEO68chD0gurqcTA load;
	tyProc__AL9bRLkzEO68chD0gurqcTA appear;
	tyProc__AL9bRLkzEO68chD0gurqcTA disappear;
	tyProc__AL9bRLkzEO68chD0gurqcTA unload;
};
struct tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w {
	NI16 x;
	NI16 y;
};
struct tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg {
	NI16 w;
	NI16 h;
};
struct tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg {
	tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w origin;
	tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg size;
};
struct tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA {
	char dummy;
};
typedef N_CDECL_PTR(void, tyProc__32w2ZypAyMWuajvi2Jt79cg) (void* a0_p0);
typedef NI32 tyEnum_enum_ButtonId570425848__Rzy1M9a2qUvvKVCZfJa2Ciw;
typedef N_CDECL_PTR(void, tyProc__LCJy9bQFEE8ObaRc29a4n3LA) (void* a0_p0, void* a1_p1);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ {
	char dummy;
};
typedef NI32 tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA;
N_LIB_PRIVATE N_CDECL(void, main)(void);
N_LIB_PRIVATE N_CDECL(void, init__action95bar95demo_u141)(void);
N_CDECL(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*, window_create)(void);
N_CDECL(void, window_set_window_handlers)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0, tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ handlers_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_CDECL(void, windowLoad__action95bar95demo_u51)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0);
N_CDECL(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*, window_get_root_layer)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0);
N_CDECL(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, layer_get_bounds)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* layer_p0);
N_CDECL(tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA*, action_bar_layer_create)(void);
N_CDECL(void, action_bar_layer_add_to_window)(tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA* action_bar_p0, tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p1);
N_CDECL(void, action_bar_layer_set_click_config_provider)(tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA* action_bar_p0, tyProc__32w2ZypAyMWuajvi2Jt79cg click_config_provider_p1);
N_LIB_PRIVATE N_CDECL(void, clickConfigProvider__action95bar95demo_u49)(void* context_p0);
N_CDECL(void, window_single_click_subscribe)(tyEnum_enum_ButtonId570425848__Rzy1M9a2qUvvKVCZfJa2Ciw button_id_p0, tyProc__LCJy9bQFEE8ObaRc29a4n3LA handler_p1);
N_LIB_PRIVATE N_CDECL(void, selectClickHandler__action95bar95demo_u31)(void* recognizer_p0, void* context_p1);
N_LIB_PRIVATE N_NIMCALL(void, updateDisplay__action95bar95demo_u8)(void);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_CDECL(void, text_layer_set_text)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, NCSTRING text_p1);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_CDECL(void, upClickHandler__action95bar95demo_u39)(void* recognizer_p0, void* context_p1);
N_LIB_PRIVATE N_CDECL(void, downClickHandler__action95bar95demo_u46)(void* recognizer_p0, void* context_p1);
N_CDECL(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*, text_layer_create)(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg frame_p0);
static N_INLINE(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3);
N_CDECL(void, text_layer_set_text_alignment)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA text_alignment_p1);
N_CDECL(void, text_layer_set_font)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng* font_p1);
N_CDECL(tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng*, fonts_get_system_font)(NCSTRING font_key_p0);
N_CDECL(void, layer_add_child)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* parent_p0, tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* child_p1);
N_CDECL(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*, text_layer_get_layer)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0);
N_LIB_PRIVATE N_CDECL(void, windowUnload__action95bar95demo_u139)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0);
N_CDECL(void, action_bar_layer_destroy)(tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA* action_bar_layer_p0);
N_CDECL(void, text_layer_destroy)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0);
N_CDECL(void, window_stack_push)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0, NIM_BOOL animated_p1);
static N_INLINE(void, eventLoop__OOZOOZOOZsrcZnebbleZapp_u2)(void);
N_CDECL(void, app_event_loop)(void);
N_LIB_PRIVATE N_CDECL(void, deinit__action95bar95demo_u193)(void);
N_CDECL(void, window_destroy)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__30PreSQGVnvXAFm9cCRkS8Q_2 = { 7 | NIM_STRLIT_FLAG, "Count: " };
static const NimStringV2 TM__30PreSQGVnvXAFm9cCRkS8Q_3 = {7, (NimStrPayload*)&TM__30PreSQGVnvXAFm9cCRkS8Q_2};
N_LIB_PRIVATE tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window__action95bar95demo_u3;
N_LIB_PRIVATE tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA* actionBar__action95bar95demo_u4;
N_LIB_PRIVATE tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* textLayer__action95bar95demo_u5;
N_LIB_PRIVATE tyArray__x9aRkN8DVcTBDUl3hEPJutg textBuffer__action95bar95demo_u6;
N_LIB_PRIVATE NI counter__action95bar95demo_u7 = ((NI)0);
extern NIM_BOOL nimInErrorMode__system_u3510;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3510);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, updateDisplay__action95bar95demo_u8)(void) {
	NimStringV2 text_1;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	text_1.len = 0; text_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = dollar___systemZdollars_u14(counter__action95bar95demo_u7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 7);
appendString((&T1_), TM__30PreSQGVnvXAFm9cCRkS8Q_3);
appendString((&T1_), colontmpD_);
	text_1 = T1_;
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((text_1.len <= ((NI)31)) ? text_1.len : ((NI)31));
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA4;
				i_1 = i_2;
				textBuffer__action95bar95demo_u6[(i_1)- 0] = text_1.p->data[i_1];
				i_2 += ((NI)1);
			} LA4: ;
		}
	}
	textBuffer__action95bar95demo_u6[(((text_1.len <= ((NI)31)) ? text_1.len : ((NI)31)))- 0] = 0;
	text_layer_set_text(textLayer__action95bar95demo_u5, ((NCSTRING) ((&textBuffer__action95bar95demo_u6[(((NI)0))- 0]))));
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	if (text_1.p && !(text_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(text_1.p);
}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, selectClickHandler__action95bar95demo_u31)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__action95bar95demo_u7 += ((NI)1);
	updateDisplay__action95bar95demo_u8();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, upClickHandler__action95bar95demo_u39)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__action95bar95demo_u7 += ((NI)10);
	updateDisplay__action95bar95demo_u8();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, downClickHandler__action95bar95demo_u46)(void* recognizer_p0, void* context_p1) {
	counter__action95bar95demo_u7 = ((NI)0);
	text_layer_set_text(textLayer__action95bar95demo_u5, "Reset!");
}
N_LIB_PRIVATE N_CDECL(void, clickConfigProvider__action95bar95demo_u49)(void* context_p0) {
	window_single_click_subscribe(((tyEnum_enum_ButtonId570425848__Rzy1M9a2qUvvKVCZfJa2Ciw)2), selectClickHandler__action95bar95demo_u31);
	window_single_click_subscribe(((tyEnum_enum_ButtonId570425848__Rzy1M9a2qUvvKVCZfJa2Ciw)1), upClickHandler__action95bar95demo_u39);
	window_single_click_subscribe(((tyEnum_enum_ButtonId570425848__Rzy1M9a2qUvvKVCZfJa2Ciw)3), downClickHandler__action95bar95demo_u46);
}
static N_INLINE(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3) {
	tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg result;
	nimZeroMem((void*)(&result), sizeof(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg));
	result.origin.x = x_p0;
	result.origin.y = y_p1;
	result.size.w = w_p2;
	result.size.h = h_p3;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, windowLoad__action95bar95demo_u51)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0) {
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* rootLayer_1;
	tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg bounds_1;
	NI16 textWidth_1;
	tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg T1_;
	tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng* T2_;
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	rootLayer_1 = window_get_root_layer(win_p0);
	bounds_1 = layer_get_bounds(rootLayer_1);
	actionBar__action95bar95demo_u4 = action_bar_layer_create();
	action_bar_layer_add_to_window(actionBar__action95bar95demo_u4, win_p0);
	action_bar_layer_set_click_config_provider(actionBar__action95bar95demo_u4, clickConfigProvider__action95bar95demo_u49);
	textWidth_1 = (NI16)(bounds_1.size.w - ((NI16)30));
	T1_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)60), textWidth_1, ((NI16)50));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textLayer__action95bar95demo_u5 = text_layer_create(T1_);
	text_layer_set_text(textLayer__action95bar95demo_u5, "Use buttons!");
	text_layer_set_text_alignment(textLayer__action95bar95demo_u5, ((tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA)1));
	T2_ = (tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng*)0;
	T2_ = fonts_get_system_font("RESOURCE_ID_GOTHIC_24_BOLD");
	text_layer_set_font(textLayer__action95bar95demo_u5, T2_);
	T3_ = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
	T3_ = text_layer_get_layer(textLayer__action95bar95demo_u5);
	layer_add_child(rootLayer_1, T3_);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, windowUnload__action95bar95demo_u139)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0) {
	action_bar_layer_destroy(actionBar__action95bar95demo_u4);
	text_layer_destroy(textLayer__action95bar95demo_u5);
}
N_LIB_PRIVATE N_CDECL(void, init__action95bar95demo_u141)(void) {
	tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ T1_;
	window__action95bar95demo_u3 = window_create();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ));
	T1_.load = windowLoad__action95bar95demo_u51;
	T1_.unload = windowUnload__action95bar95demo_u139;
	window_set_window_handlers(window__action95bar95demo_u3, T1_);
	window_stack_push(window__action95bar95demo_u3, NIM_TRUE);
}
static N_INLINE(void, eventLoop__OOZOOZOOZsrcZnebbleZapp_u2)(void) {
	app_event_loop();
}
N_LIB_PRIVATE N_CDECL(void, deinit__action95bar95demo_u193)(void) {
	window_destroy(window__action95bar95demo_u3);
}
N_LIB_PRIVATE N_CDECL(void, main)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	init__action95bar95demo_u141();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eventLoop__OOZOOZOOZsrcZnebbleZapp_u2();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	deinit__action95bar95demo_u193();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, NimDestroyGlobals)(void) {
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

