/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg;
typedef struct tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA;
typedef struct tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ;
typedef struct tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA;
struct tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg {
	tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA* pRaw;
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* pParent;
	tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* attachedWindow;
};
struct tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA {
	char dummy;
};
struct tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA {
	char dummy;
};
struct tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ {
	char dummy;
};
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZaction95bar_u7)(tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg* h_p0);
N_CDECL(void, action_bar_layer_destroy)(tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA* action_bar_layer_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_BOOL nimInErrorMode__system_u3510;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZaction95bar_u7)(tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg* h_p0) {
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = !(((*h_p0).pRaw == ((tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA*) NIM_NIL)));
		if (!(T4_)) goto LA5_;
		T4_ = ((*h_p0).attachedWindow == ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL));
LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA6_;
		T3_ = ((*h_p0).pParent == ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL));
LA6_: ;
		if (!T3_) goto LA7_;
		action_bar_layer_destroy((*h_p0).pRaw);
	}
LA7_: ;
	(*h_p0).pRaw = ((tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA*) NIM_NIL);
	(*h_p0).attachedWindow = ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL);
	(*h_p0).pParent = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3510);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZaction95bar_u42)(tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg* dest_p0, tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg src_p1) {
	tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg* srcPtr_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZaction95bar_u7(dest_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*dest_p0).pRaw = src_p1.pRaw;
	(*dest_p0).attachedWindow = src_p1.attachedWindow;
	(*dest_p0).pParent = src_p1.pParent;
	srcPtr_1 = ((tyObject_ActionBarLayerHandle__DsZ3uDf7iYQU3yX00y7WMg*) ((&src_p1)));
	(*srcPtr_1).pRaw = ((tyObject_struct_ActionBarLayer__WTvPbtZjrbDUaeqziPvLOA*) NIM_NIL);
	(*srcPtr_1).attachedWindow = ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL);
	(*srcPtr_1).pParent = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
	}BeforeRet_: ;
}
