/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A;
typedef struct tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ;
typedef struct tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA;
typedef struct tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw;
typedef struct tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A;
typedef struct tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w;
typedef struct tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw;
typedef struct tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q;
typedef struct tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw;
typedef struct tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg;
typedef struct tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q;
typedef union tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw;
typedef struct tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w;
typedef struct tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA;
typedef NU8 tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw;
struct tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A {
	tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* raw;
	tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw state;
};
struct tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* pRaw;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* pParent;
};
typedef NIM_CHAR tyArray__x9aRkN8DVcTBDUl3hEPJutg[32];
struct tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w {
	NI len;
	tyArray__x9aRkN8DVcTBDUl3hEPJutg data;
};
typedef NIM_CHAR tyArray__2cWMSJoP9cqN4yIK0ILkQaQ[64];
struct tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw {
	NI len;
	tyArray__2cWMSJoP9cqN4yIK0ILkQaQ data;
};
struct tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ {
	char dummy;
};
typedef N_CDECL_PTR(void, tyProc__YKpbB7RnAWujFAITf8zLgw) (tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* a0_p0);
struct tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q {
	tyProc__YKpbB7RnAWujFAITf8zLgw load;
	tyProc__YKpbB7RnAWujFAITf8zLgw appear;
	tyProc__YKpbB7RnAWujFAITf8zLgw disappear;
	tyProc__YKpbB7RnAWujFAITf8zLgw unload;
};
struct tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg {
	NI16 x;
	NI16 y;
};
struct tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q {
	NI16 w;
	NI16 h;
};
struct tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw {
	tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg origin;
	tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q size;
};
struct tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw {
	char dummy;
};
struct tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w {
	NU8 b:2;
	NU8 g:2;
	NU8 r:2;
	NU8 a:2;
};
union tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw {
	NU8 argb;
	tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w anon0;
};
typedef NI32 tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA;
struct tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A {
	char dummy;
};
typedef N_CDECL_PTR(void, tyProc__32w2ZypAyMWuajvi2Jt79cg) (void* a0_p0);
typedef NI32 tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q;
typedef N_CDECL_PTR(void, tyProc__LCJy9bQFEE8ObaRc29a4n3LA) (void* a0_p0, void* a1_p1);
typedef NIM_CHAR tyArray__0j8sSXZOeBGmu6W0H2n0Uw[10];
N_LIB_PRIVATE N_CDECL(int, main)(void);
N_NIMCALL(void, NimMain)(void);
N_LIB_PRIVATE N_CDECL(void, init__persist95demo_u199)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* dest_p0, tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A src_p1);
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189)(void);
N_CDECL(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*, window_create)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0);
static N_INLINE(void, setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u267)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyProc__YKpbB7RnAWujFAITf8zLgw load_p1, tyProc__YKpbB7RnAWujFAITf8zLgw unload_p2, tyProc__YKpbB7RnAWujFAITf8zLgw appear_p3, tyProc__YKpbB7RnAWujFAITf8zLgw disappear_p4);
N_CDECL(void, window_set_window_handlers)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q handlers_p1);
N_LIB_PRIVATE N_CDECL(void, windowLoad__persist95demo_u103)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* destX60gensym0__p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA srcX60gensym0__p1);
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u114)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0);
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayerHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u111)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0);
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, wrapOwned__OOZOOZOOZsrcZnebbleZuiZtext95layer_u86)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* pX60gensym0__p0);
N_CDECL(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*, text_layer_create)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0);
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* hX60gensym0__p0);
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u163)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw value_p1);
N_CDECL(void, text_layer_set_background_color)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1);
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw* Result);
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u145)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* value_p1);
N_CDECL(void, text_layer_set_font)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* font_p1);
N_CDECL(tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*, fonts_get_system_font)(NCSTRING font_key_p0);
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u136)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, NCSTRING value_p1);
N_CDECL(void, text_layer_set_text)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, NCSTRING text_p1);
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u151)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA value_p1);
N_CDECL(void, text_layer_set_text_alignment)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA text_alignment_p1);
static N_INLINE(NCSTRING, toCstring__persist95demo_u105)(tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p0);
static N_INLINE(void, addChild__persist95demo_u136)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* child_p1);
N_CDECL(void, layer_add_child)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* child_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, toLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u77)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA hX60gensym0__p0);
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0);
N_CDECL(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, window_get_root_layer)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0);
static N_INLINE(void, clickConfigeq___OOZOOZOOZsrcZnebbleZuiZwindow_u325)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0, tyProc__32w2ZypAyMWuajvi2Jt79cg provider_p1);
N_CDECL(void, window_set_click_config_provider)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, tyProc__32w2ZypAyMWuajvi2Jt79cg click_config_provider_p1);
N_LIB_PRIVATE N_CDECL(void, generatedClickConfigProvider__persist95demo_u96)(void* ctxX60gensym64__p0);
static N_INLINE(void, onClick__OOZOOZOOZsrcZnebbleZuiZclicks_u2)(tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q buttonId_p0, tyProc__LCJy9bQFEE8ObaRc29a4n3LA handler_p1);
N_CDECL(void, window_single_click_subscribe)(tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q button_id_p0, tyProc__LCJy9bQFEE8ObaRc29a4n3LA handler_p1);
N_LIB_PRIVATE N_CDECL(void, selectClickHandler__persist95demo_u6)(void* recognizer_p0, void* context_p1);
N_LIB_PRIVATE N_NIMCALL(void, saveData__persist95demo_u17)(void);
static N_INLINE(int, writeInt__OOZOOZOOZsrcZnebbleZfoundationZstorage_u9)(NU32 key_p0, NI32 value_p1);
N_CDECL(NI32, persist_write_int)(NU32 key_p0, NI32 value_p1);
N_LIB_PRIVATE N_NIMCALL(void, updateDisplay__persist95demo_u16)(void);
static N_INLINE(void, clear__persist95demo_u216)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0);
static N_INLINE(void, add__persist95demo_u255)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0, NCSTRING str_p1);
static N_INLINE(NIM_BOOL, eqeq___system_u6018)(NCSTRING x_p0, NCSTRING y_p1);
static N_INLINE(void, addInt__persist95demo_u282)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0, NI32 val_p1);
static N_INLINE(void, add__persist95demo_u299)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0, NIM_CHAR c_p1);
static N_INLINE(NCSTRING, toCstring__persist95demo_u398)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0);
static N_INLINE(void, shortPulse__OOZOOZOOZsrcZnebbleZuiZvibes_u2)(void);
N_CDECL(void, vibes_short_pulse)(void);
N_LIB_PRIVATE N_CDECL(void, upClickHandler__persist95demo_u9)(void* recognizer_p0, void* context_p1);
N_LIB_PRIVATE N_CDECL(void, downClickHandler__persist95demo_u12)(void* recognizer_p0, void* context_p1);
static N_INLINE(void, doublePulse__OOZOOZOOZsrcZnebbleZuiZvibes_u4)(void);
N_CDECL(void, vibes_double_pulse)(void);
N_LIB_PRIVATE N_CDECL(void, windowUnload__persist95demo_u180)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0);
static N_INLINE(void, push__OOZOOZOOZsrcZnebbleZuiZwindow_u199)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, NIM_BOOL animated_p1);
N_CDECL(void, window_stack_push)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, NIM_BOOL animated_p1);
N_LIB_PRIVATE N_NIMCALL(void, loadData__persist95demo_u15)(void);
static N_INLINE(NIM_BOOL, exists__OOZOOZOOZsrcZnebbleZfoundationZstorage_u3)(NU32 key_p0);
N_CDECL(NIM_BOOL, persist_exists)(NU32 key_p0);
static N_INLINE(NI32, readInt__OOZOOZOOZsrcZnebbleZfoundationZstorage_u6)(NU32 key_p0);
N_CDECL(NI32, persist_read_int)(NU32 key_p0);
static N_INLINE(int, read__persist95demo_u414)(NU32 key_p0, tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p1);
N_CDECL(int, persist_read_string)(NU32 key_p0, NCSTRING buffer_p1, size_t buffer_size_p2);
static N_INLINE(void, clear__persist95demo_u441)(tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p0);
static N_INLINE(void, add__persist95demo_u458)(tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p0, NCSTRING str_p1);
N_CDECL(void, app_event_loop)(void);
N_LIB_PRIVATE N_CDECL(void, deinit__persist95demo_u200)(void);
static N_INLINE(NIM_BOOL, pop__OOZOOZOOZsrcZnebbleZuiZwindow_u202)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0);
N_CDECL(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*, window_stack_get_top_window)(void);
N_CDECL(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*, window_stack_pop)(NIM_BOOL animated_p0);
N_LIB_PRIVATE N_CDECL(void, _exit)(int codeX60gensym66__p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A pebbleWindow__persist95demo_u98;
N_LIB_PRIVATE tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA titleLayer__persist95demo_u99;
N_LIB_PRIVATE tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA nameLayer__persist95demo_u100;
N_LIB_PRIVATE tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA counterLayer__persist95demo_u101;
N_LIB_PRIVATE tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA instrLayer__persist95demo_u102;
N_LIB_PRIVATE NI32 counter__persist95demo_u18 = ((NI32)0);
N_LIB_PRIVATE tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w counterStr__persist95demo_u28;
N_LIB_PRIVATE tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw nameStr__persist95demo_u37;
extern NIM_BOOL nimInErrorMode__system_u3510;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3510);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A result;
	nimZeroMem((void*)(&result), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
	result.raw = window_create();
	result.state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)0);
	return result;
}
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
	result = newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u267)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyProc__YKpbB7RnAWujFAITf8zLgw load_p1, tyProc__YKpbB7RnAWujFAITf8zLgw unload_p2, tyProc__YKpbB7RnAWujFAITf8zLgw appear_p3, tyProc__YKpbB7RnAWujFAITf8zLgw disappear_p4) {
	tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q handlers_1;
	nimZeroMem((void*)(&handlers_1), sizeof(tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q));
	{
		if (!!((load_p1 == NIM_NIL))) goto LA3_;
		handlers_1.load = load_p1;
	}
LA3_: ;
	{
		if (!!((unload_p2 == NIM_NIL))) goto LA7_;
		handlers_1.unload = unload_p2;
	}
LA7_: ;
	{
		if (!!((appear_p3 == NIM_NIL))) goto LA11_;
		handlers_1.appear = appear_p3;
	}
LA11_: ;
	{
		if (!!((disappear_p4 == NIM_NIL))) goto LA15_;
		handlers_1.disappear = disappear_p4;
	}
LA15_: ;
	window_set_window_handlers((*h_p0).raw, handlers_1);
}
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, wrapOwned__OOZOOZOOZsrcZnebbleZuiZtext95layer_u86)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* pX60gensym0__p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA result;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* colontmpD_;
	colontmpD_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	colontmpD_ = pX60gensym0__p0;
	result.pRaw = colontmpD_;
	result.pParent = ((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL);
	return result;
}
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayerHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u111)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA result;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	T1_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T1_ = text_layer_create(frame_p0);
	result = wrapOwned__OOZOOZOOZsrcZnebbleZuiZtext95layer_u86(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u114)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	result = newTextLayerHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u111(frame_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3) {
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw));
	result.origin.x = x_p0;
	result.origin.y = y_p1;
	result.size.w = w_p2;
	result.size.h = h_p3;
	return result;
}
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u163)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw value_p1) {
	text_layer_set_background_color((*h_p0).pRaw, value_p1);
}
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	(*Result).argb = argb_p0;
}
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u145)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* value_p1) {
	text_layer_set_font((*h_p0).pRaw, value_p1);
}
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u136)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, NCSTRING value_p1) {
	text_layer_set_text((*h_p0).pRaw, value_p1);
}
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u151)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA value_p1) {
	text_layer_set_text_alignment((*h_p0).pRaw, value_p1);
}
static N_INLINE(NCSTRING, toCstring__persist95demo_u105)(tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p0) {
	NCSTRING result;
	result = ((NCSTRING) ((&(*s_p0).data[(((NI)0))- 0])));
	return result;
}
static N_INLINE(void, addChild__persist95demo_u136)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* child_p1) {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T1_ = toLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u77((*child_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	layer_add_child(parent_p0, T1_);
	}BeforeRet_: ;
}
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0) {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* result;
	result = window_get_root_layer(win_p0);
	return result;
}
static N_INLINE(void, clickConfigeq___OOZOOZOOZsrcZnebbleZuiZwindow_u325)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0, tyProc__32w2ZypAyMWuajvi2Jt79cg provider_p1) {
	window_set_click_config_provider(win_p0, provider_p1);
}
static N_INLINE(void, onClick__OOZOOZOOZsrcZnebbleZuiZclicks_u2)(tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q buttonId_p0, tyProc__LCJy9bQFEE8ObaRc29a4n3LA handler_p1) {
	window_single_click_subscribe(buttonId_p0, handler_p1);
}
static N_INLINE(int, writeInt__OOZOOZOOZsrcZnebbleZfoundationZstorage_u9)(NU32 key_p0, NI32 value_p1) {
	int result;
	result = persist_write_int(key_p0, value_p1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, saveData__persist95demo_u17)(void) {
	int T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (int)0;
	T1_ = writeInt__OOZOOZOOZsrcZnebbleZfoundationZstorage_u9(((NU32)1), counter__persist95demo_u18);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T1_);
	}BeforeRet_: ;
}
static N_INLINE(void, clear__persist95demo_u216)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0) {
	(*s_p0).len = ((NI)0);
	(*s_p0).data[(((NI)0))- 0] = 0;
}
static N_INLINE(NIM_BOOL, eqeq___system_u6018)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, add__persist95demo_u255)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0, NCSTRING str_p1) {
	NI i_1;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq___system_u6018(str_p1, ((NCSTRING) NIM_NIL));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	i_1 = ((NI)0);
	{
		while (1) {
			NIM_BOOL T8_;
			T8_ = (NIM_BOOL)0;
			T8_ = !(((NU8)(str_p1[i_1]) == (NU8)(0)));
			if (!(T8_)) goto LA9_;
			T8_ = ((*s_p0).len < ((NI)31));
LA9_: ;
			if (!T8_) goto LA7;
			(*s_p0).data[((*s_p0).len)- 0] = str_p1[i_1];
			(*s_p0).len += ((NI)1);
			i_1 += ((NI)1);
		} LA7: ;
	}
	(*s_p0).data[((*s_p0).len)- 0] = 0;
	}BeforeRet_: ;
}
static N_INLINE(void, add__persist95demo_u299)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0, NIM_CHAR c_p1) {
	{
		if (!((*s_p0).len < ((NI)31))) goto LA3_;
		(*s_p0).data[((*s_p0).len)- 0] = c_p1;
		(*s_p0).len += ((NI)1);
		(*s_p0).data[((*s_p0).len)- 0] = 0;
	}
LA3_: ;
}
static N_INLINE(void, addInt__persist95demo_u282)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0, NI32 val_p1) {
	NI32 v_1;
	tyArray__0j8sSXZOeBGmu6W0H2n0Uw digits_1;
	NI count_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(((NI)31) <= (*s_p0).len)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(val_p1 == ((NI32)0))) goto LA7_;
		add__persist95demo_u299(s_p0, 48);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	v_1 = val_p1;
	{
		if (!(v_1 < ((NI32)0))) goto LA11_;
		add__persist95demo_u299(s_p0, 45);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		v_1 = ((NI32)-(v_1));
	}
LA11_: ;
	nimZeroMem((void*)digits_1, sizeof(tyArray__0j8sSXZOeBGmu6W0H2n0Uw));
	count_1 = ((NI)0);
	{
		while (1) {
			NIM_BOOL T15_;
			T15_ = (NIM_BOOL)0;
			T15_ = (((NI32)0) < v_1);
			if (!(T15_)) goto LA16_;
			T15_ = (count_1 < ((NI)10));
LA16_: ;
			if (!T15_) goto LA14;
			digits_1[(count_1)- 0] = ((NIM_CHAR) ((NI32)(((NI32)48) + (NI32)(v_1 % ((NI32)10)))));
			v_1 = (NI32)(v_1 / ((NI32)10));
			count_1 += ((NI)1);
		} LA14: ;
	}
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(count_1 - ((NI)1));
		res_1 = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res_1)) goto LA19;
				i_1 = ((NI) (res_1));
				add__persist95demo_u299(s_p0, digits_1[(i_1)- 0]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				res_1 -= ((NI)1);
			} LA19: ;
		}
	}
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, toCstring__persist95demo_u398)(tyObject_FixedString__xa1xApmG6K4Owp23GMXv3w* s_p0) {
	NCSTRING result;
	result = ((NCSTRING) ((&(*s_p0).data[(((NI)0))- 0])));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, updateDisplay__persist95demo_u16)(void) {
	NCSTRING T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	clear__persist95demo_u216((&counterStr__persist95demo_u28));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	add__persist95demo_u255((&counterStr__persist95demo_u28), "Counter: ");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addInt__persist95demo_u282((&counterStr__persist95demo_u28), counter__persist95demo_u18);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = (NCSTRING)0;
	T1_ = toCstring__persist95demo_u398((&counterStr__persist95demo_u28));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u136((&counterLayer__persist95demo_u101), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, shortPulse__OOZOOZOOZsrcZnebbleZuiZvibes_u2)(void) {
	vibes_short_pulse();
}
N_LIB_PRIVATE N_CDECL(void, selectClickHandler__persist95demo_u6)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__persist95demo_u18 += ((NI)1);
	saveData__persist95demo_u17();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u16();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!((NI32)(counter__persist95demo_u18 % ((NI32)10)) == ((NI32)0))) goto LA3_;
		shortPulse__OOZOOZOOZsrcZnebbleZuiZvibes_u2();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, upClickHandler__persist95demo_u9)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__persist95demo_u18 += ((NI32)10);
	saveData__persist95demo_u17();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u16();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, doublePulse__OOZOOZOOZsrcZnebbleZuiZvibes_u4)(void) {
	vibes_double_pulse();
}
N_LIB_PRIVATE N_CDECL(void, downClickHandler__persist95demo_u12)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__persist95demo_u18 = ((NI32)0);
	saveData__persist95demo_u17();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u16();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	doublePulse__OOZOOZOOZsrcZnebbleZuiZvibes_u4();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, generatedClickConfigProvider__persist95demo_u96)(void* ctxX60gensym64__p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	onClick__OOZOOZOOZsrcZnebbleZuiZclicks_u2(((tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q)2), selectClickHandler__persist95demo_u6);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	onClick__OOZOOZOOZsrcZnebbleZuiZclicks_u2(((tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q)1), upClickHandler__persist95demo_u9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	onClick__OOZOOZOOZsrcZnebbleZuiZclicks_u2(((tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q)3), downClickHandler__persist95demo_u12);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, windowLoad__persist95demo_u103)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0) {
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T1_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T2_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T3_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T4_;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T5_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T6_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T7_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T8_;
	NCSTRING T9_;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T10_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T11_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T12_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T13_;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T14_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T15_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T16_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T17_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)20), ((NI16)144), ((NI16)30));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u114(T1_);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23(&T2_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&titleLayer__persist95demo_u99), T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T3_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T3_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u163((&titleLayer__persist95demo_u99), T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T4_ = fonts_get_system_font("RESOURCE_ID_GOTHIC_24_BOLD");
	fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u145((&titleLayer__persist95demo_u99), T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u136((&titleLayer__persist95demo_u99), "Persist Demo");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u151((&titleLayer__persist95demo_u99), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T5_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)55), ((NI16)144), ((NI16)25));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u114(T5_);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23(&T6_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&nameLayer__persist95demo_u100), T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T7_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T7_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u163((&nameLayer__persist95demo_u100), T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T8_ = fonts_get_system_font("RESOURCE_ID_GOTHIC_18");
	fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u145((&nameLayer__persist95demo_u100), T8_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T9_ = (NCSTRING)0;
	T9_ = toCstring__persist95demo_u105((&nameStr__persist95demo_u37));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u136((&nameLayer__persist95demo_u100), T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u151((&nameLayer__persist95demo_u100), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T10_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)85), ((NI16)144), ((NI16)35));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T11_ = newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u114(T10_);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23(&T11_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&counterLayer__persist95demo_u101), T11_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T12_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T12_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u163((&counterLayer__persist95demo_u101), T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T13_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T13_ = fonts_get_system_font("RESOURCE_ID_GOTHIC_28_BOLD");
	fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u145((&counterLayer__persist95demo_u101), T13_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u151((&counterLayer__persist95demo_u101), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T14_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)125), ((NI16)144), ((NI16)40));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T15_ = newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u114(T14_);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23(&T15_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&instrLayer__persist95demo_u102), T15_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T16_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T16_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u163((&instrLayer__persist95demo_u102), T16_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T17_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T17_ = fonts_get_system_font("RESOURCE_ID_GOTHIC_14");
	fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u145((&instrLayer__persist95demo_u102), T17_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u136((&instrLayer__persist95demo_u102), "SELECT: +1\012UP: +10\012DOWN: Reset");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u151((&instrLayer__persist95demo_u102), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!!((((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL) == ((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL)))) goto LA20_;
		addChild__persist95demo_u136(((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL), (&titleLayer__persist95demo_u99));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA18_;
LA20_: ;
	{
		tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T23_;
		T23_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
		T23_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230(win_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		addChild__persist95demo_u136(T23_, (&titleLayer__persist95demo_u99));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA18_: ;
	{
		if (!!((((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL) == ((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL)))) goto LA26_;
		addChild__persist95demo_u136(((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL), (&nameLayer__persist95demo_u100));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA24_;
LA26_: ;
	{
		tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T29_;
		T29_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
		T29_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230(win_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		addChild__persist95demo_u136(T29_, (&nameLayer__persist95demo_u100));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA24_: ;
	{
		if (!!((((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL) == ((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL)))) goto LA32_;
		addChild__persist95demo_u136(((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL), (&counterLayer__persist95demo_u101));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA30_;
LA32_: ;
	{
		tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T35_;
		T35_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
		T35_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230(win_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		addChild__persist95demo_u136(T35_, (&counterLayer__persist95demo_u101));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA30_: ;
	{
		if (!!((((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL) == ((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL)))) goto LA38_;
		addChild__persist95demo_u136(((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL), (&instrLayer__persist95demo_u102));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA36_;
LA38_: ;
	{
		tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T41_;
		T41_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
		T41_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230(win_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		addChild__persist95demo_u136(T41_, (&instrLayer__persist95demo_u102));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA36_: ;
	clickConfigeq___OOZOOZOOZsrcZnebbleZuiZwindow_u325(win_p0, generatedClickConfigProvider__persist95demo_u96);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, windowUnload__persist95demo_u180)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T1_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T2_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T3_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&titleLayer__persist95demo_u99), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T2_), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&nameLayer__persist95demo_u100), T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T3_), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&counterLayer__persist95demo_u101), T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T4_), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u54((&instrLayer__persist95demo_u102), T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, push__OOZOOZOOZsrcZnebbleZuiZwindow_u199)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, NIM_BOOL animated_p1) {
	window_stack_push((*h_p0).raw, animated_p1);
	(*h_p0).state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)1);
}
static N_INLINE(NIM_BOOL, exists__OOZOOZOOZsrcZnebbleZfoundationZstorage_u3)(NU32 key_p0) {
	NIM_BOOL result;
	result = persist_exists(key_p0);
	return result;
}
static N_INLINE(NI32, readInt__OOZOOZOOZsrcZnebbleZfoundationZstorage_u6)(NU32 key_p0) {
	NI32 result;
	result = persist_read_int(key_p0);
	return result;
}
static N_INLINE(int, read__persist95demo_u414)(NU32 key_p0, tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p1) {
	int result;
	int res_1;
	NCSTRING T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (int)0;
	T1_ = (NCSTRING)0;
	T1_ = toCstring__persist95demo_u105(s_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	res_1 = persist_read_string(key_p0, T1_, ((size_t)64));
	{
		if (!(((NI32)0) <= res_1)) goto LA4_;
		(*s_p1).len = ((NI) (res_1));
	}
LA4_: ;
	result = res_1;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, clear__persist95demo_u441)(tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p0) {
	(*s_p0).len = ((NI)0);
	(*s_p0).data[(((NI)0))- 0] = 0;
}
static N_INLINE(void, add__persist95demo_u458)(tyObject_FixedString__FEvMMAl6BfSkYl1B6N5cOw* s_p0, NCSTRING str_p1) {
	NI i_1;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq___system_u6018(str_p1, ((NCSTRING) NIM_NIL));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	i_1 = ((NI)0);
	{
		while (1) {
			NIM_BOOL T8_;
			T8_ = (NIM_BOOL)0;
			T8_ = !(((NU8)(str_p1[i_1]) == (NU8)(0)));
			if (!(T8_)) goto LA9_;
			T8_ = ((*s_p0).len < ((NI)63));
LA9_: ;
			if (!T8_) goto LA7;
			(*s_p0).data[((*s_p0).len)- 0] = str_p1[i_1];
			(*s_p0).len += ((NI)1);
			i_1 += ((NI)1);
		} LA7: ;
	}
	(*s_p0).data[((*s_p0).len)- 0] = 0;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, loadData__persist95demo_u15)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		NI32 T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = exists__OOZOOZOOZsrcZnebbleZfoundationZstorage_u3(((NU32)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = (NI32)0;
		T6_ = readInt__OOZOOZOOZsrcZnebbleZfoundationZstorage_u6(((NU32)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		counter__persist95demo_u18 = T6_;
	}
	goto LA1_;
LA4_: ;
	{
		counter__persist95demo_u18 = ((NI32)0);
	}
LA1_: ;
	{
		NIM_BOOL T10_;
		int T13_;
		T10_ = (NIM_BOOL)0;
		T10_ = exists__OOZOOZOOZsrcZnebbleZfoundationZstorage_u3(((NU32)2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T10_) goto LA11_;
		T13_ = (int)0;
		T13_ = read__persist95demo_u414(((NU32)2), (&nameStr__persist95demo_u37));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T13_);
	}
	goto LA8_;
LA11_: ;
	{
		clear__persist95demo_u441((&nameStr__persist95demo_u37));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		add__persist95demo_u458((&nameStr__persist95demo_u37), "Nebble User");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA8_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, init__persist95demo_u199)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7(&T1_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50((&pebbleWindow__persist95demo_u98), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u267((&pebbleWindow__persist95demo_u98), windowLoad__persist95demo_u103, windowUnload__persist95demo_u180, NIM_NIL, NIM_NIL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	push__OOZOOZOOZsrcZnebbleZuiZwindow_u199((&pebbleWindow__persist95demo_u98), NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadData__persist95demo_u15();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u16();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, pop__OOZOOZOOZsrcZnebbleZuiZwindow_u202)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0) {
	NIM_BOOL result;
{	{
		tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* topWindow_1;
		if (!((*h_p0).state == ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)1))) goto LA3_;
		topWindow_1 = window_stack_get_top_window();
		{
			tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* popped_1;
			if (!(topWindow_1 == (*h_p0).raw)) goto LA7_;
			popped_1 = window_stack_pop(NIM_TRUE);
			{
				if (!(popped_1 == (*h_p0).raw)) goto LA11_;
				(*h_p0).state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)2);
				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA11_: ;
		}
		goto LA5_;
LA7_: ;
		{
		}
LA5_: ;
	}
LA3_: ;
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, deinit__persist95demo_u200)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	saveData__persist95demo_u17();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = pop__OOZOOZOOZsrcZnebbleZuiZwindow_u202((&pebbleWindow__persist95demo_u98));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimZeroMem((void*)(&T6_), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
		eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50((&pebbleWindow__persist95demo_u98), T6_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(int, main)(void) {
	int result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (int)0;
	NimMain();
	init__persist95demo_u199();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	app_event_loop();
	deinit__persist95demo_u200();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((int)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, _exit)(int codeX60gensym66__p0) {
}
N_LIB_PRIVATE N_CDECL(void, NimDestroyGlobals)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23((&instrLayer__persist95demo_u102));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23((&counterLayer__persist95demo_u101));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23((&nameLayer__persist95demo_u100));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u23((&titleLayer__persist95demo_u99));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7((&pebbleWindow__persist95demo_u98));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

