/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw;
typedef struct tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ;
typedef struct tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q;
typedef struct tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A;
typedef struct tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw;
typedef struct tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg;
typedef struct tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q;
typedef struct tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA;
typedef union tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw;
typedef struct tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NIM_CHAR tyArray__x9aRkN8DVcTBDUl3hEPJutg[32];
typedef NIM_CHAR tyArray__2cWMSJoP9cqN4yIK0ILkQaQ[64];
struct tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ {
	char dummy;
};
typedef N_CDECL_PTR(void, tyProc__YKpbB7RnAWujFAITf8zLgw) (tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* a0_p0);
struct tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q {
	tyProc__YKpbB7RnAWujFAITf8zLgw load;
	tyProc__YKpbB7RnAWujFAITf8zLgw appear;
	tyProc__YKpbB7RnAWujFAITf8zLgw disappear;
	tyProc__YKpbB7RnAWujFAITf8zLgw unload;
};
struct tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A {
	char dummy;
};
struct tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg {
	NI16 x;
	NI16 y;
};
struct tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q {
	NI16 w;
	NI16 h;
};
struct tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw {
	tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg origin;
	tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q size;
};
typedef NI32 tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA;
struct tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw {
	char dummy;
};
struct tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA {
	char dummy;
};
struct tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w {
	NU8 b:2;
	NU8 g:2;
	NU8 r:2;
	NU8 a:2;
};
union tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw {
	NU8 argb;
	tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w anon0;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_CDECL_PTR(void, tyProc__32w2ZypAyMWuajvi2Jt79cg) (void* a0_p0);
typedef NI32 tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q;
typedef N_CDECL_PTR(void, tyProc__LCJy9bQFEE8ObaRc29a4n3LA) (void* a0_p0, void* a1_p1);
N_LIB_PRIVATE N_CDECL(int, main)(void);
N_LIB_PRIVATE N_CDECL(void, init__persist95demo_u103)(void);
N_CDECL(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*, window_create)(void);
N_CDECL(void, window_set_window_handlers)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q handlers_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_CDECL(void, windowLoad__persist95demo_u93)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0);
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, rootLayer__OOZOOZOOZsrcZnebbleZwindow_u39)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0);
N_CDECL(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, window_get_root_layer)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0);
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, bounds__OOZOOZOOZsrcZnebbleZlayer_u52)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* layer_p0);
N_CDECL(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, layer_get_bounds)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* layer_p0);
static N_INLINE(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*, newTextLayer__OOZOOZOOZsrcZnebbleZtext95layer_u2)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0, NCSTRING text_p1, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* font_p2, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA align_p3);
N_CDECL(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*, text_layer_create)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u6018)(NCSTRING x_p0, NCSTRING y_p1);
N_CDECL(void, text_layer_set_text)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, NCSTRING text_p1);
N_CDECL(void, text_layer_set_font)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* font_p1);
N_CDECL(void, text_layer_set_text_alignment)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA text_alignment_p1);
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3);
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZtext95layer_u33)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, NCSTRING text_p1);
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZtext95layer_u42)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA alignment_p1);
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZtext95layer_u39)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* font_p1);
static N_INLINE(tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*, getSystemFont__OOZOOZOOZsrcZnebbleZfonts_u2)(NCSTRING fontKey_p0);
N_CDECL(tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*, fonts_get_system_font)(NCSTRING font_key_p0);
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZtext95layer_u45)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1);
N_CDECL(void, text_layer_set_background_color)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1);
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw* Result);
static N_INLINE(void, addChild__OOZOOZOOZsrcZnebbleZlayer_u11)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* child_p1);
N_CDECL(void, layer_add_child)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* child_p1);
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, getLayer__OOZOOZOOZsrcZnebbleZtext95layer_u30)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0);
N_CDECL(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, text_layer_get_layer)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0);
N_LIB_PRIVATE N_NIMCALL(void, loadData__persist95demo_u50)(void);
static N_INLINE(NIM_BOOL, exists__OOZOOZOOZsrcZnebbleZstorage_u2)(NU32 key_p0);
N_CDECL(NIM_BOOL, persist_exists)(NU32 key_p0);
static N_INLINE(NI32, readInt__OOZOOZOOZsrcZnebbleZstorage_u11)(NU32 key_p0);
N_CDECL(NI32, persist_read_int)(NU32 key_p0);
static N_INLINE(int, readString__OOZOOZOOZsrcZnebbleZstorage_u19)(NU32 key_p0, NCSTRING buffer_p1, size_t bufferSize_p2);
N_CDECL(int, persist_read_string)(NU32 key_p0, NCSTRING buffer_p1, size_t buffer_size_p2);
N_LIB_PRIVATE N_NIMCALL(void, updateDisplay__persist95demo_u12)(void);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_CDECL(void, windowUnload__persist95demo_u99)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0);
static N_INLINE(void, destroy__OOZOOZOOZsrcZnebbleZtext95layer_u28)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0);
N_CDECL(void, text_layer_destroy)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0);
N_CDECL(void, window_set_click_config_provider)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, tyProc__32w2ZypAyMWuajvi2Jt79cg click_config_provider_p1);
N_LIB_PRIVATE N_CDECL(void, clickConfigProvider__persist95demo_u91)(void* context_p0);
static N_INLINE(void, onClick__OOZOOZOOZsrcZnebbleZclicks_u2)(tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q buttonId_p0, tyProc__LCJy9bQFEE8ObaRc29a4n3LA handler_p1);
N_CDECL(void, window_single_click_subscribe)(tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q button_id_p0, tyProc__LCJy9bQFEE8ObaRc29a4n3LA handler_p1);
N_LIB_PRIVATE N_CDECL(void, selectClickHandler__persist95demo_u73)(void* recognizer_p0, void* context_p1);
N_LIB_PRIVATE N_NIMCALL(void, saveData__persist95demo_u49)(void);
static N_INLINE(NI32, writeInt__OOZOOZOOZsrcZnebbleZstorage_u28)(NU32 key_p0, NI32 value_p1);
N_CDECL(NI32, persist_write_int)(NU32 key_p0, NI32 value_p1);
static N_INLINE(void, shortPulse__OOZOOZOOZsrcZnebbleZvibes_u3)(void);
N_CDECL(void, vibes_short_pulse)(void);
N_LIB_PRIVATE N_CDECL(void, upClickHandler__persist95demo_u81)(void* recognizer_p0, void* context_p1);
N_LIB_PRIVATE N_CDECL(void, downClickHandler__persist95demo_u88)(void* recognizer_p0, void* context_p1);
static N_INLINE(void, doublePulse__OOZOOZOOZsrcZnebbleZvibes_u5)(void);
N_CDECL(void, vibes_double_pulse)(void);
N_CDECL(void, window_stack_push)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, NIM_BOOL animated_p1);
static N_INLINE(void, eventLoop__OOZOOZOOZsrcZnebbleZapp_u3)(void);
N_CDECL(void, app_event_loop)(void);
N_LIB_PRIVATE N_CDECL(void, deinit__persist95demo_u104)(void);
N_LIB_PRIVATE N_NIMCALL(void, deinitApp__persist95demo_u101)(void);
N_CDECL(void, window_destroy)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__lqeHtcRlDduU9aPt9aAEw6Dw_2 = { 11 | NIM_STRLIT_FLAG, "Nebble User" };
static const NimStringV2 TM__lqeHtcRlDduU9aPt9aAEw6Dw_3 = {11, (NimStrPayload*)&TM__lqeHtcRlDduU9aPt9aAEw6Dw_2};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__lqeHtcRlDduU9aPt9aAEw6Dw_4 = { 9 | NIM_STRLIT_FLAG, "Counter: " };
static const NimStringV2 TM__lqeHtcRlDduU9aPt9aAEw6Dw_5 = {9, (NimStrPayload*)&TM__lqeHtcRlDduU9aPt9aAEw6Dw_4};
N_LIB_PRIVATE tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* counterLayer__persist95demo_u7;
N_LIB_PRIVATE tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* nameLayer__persist95demo_u8;
N_LIB_PRIVATE tyArray__x9aRkN8DVcTBDUl3hEPJutg counterBuffer__persist95demo_u9;
N_LIB_PRIVATE tyArray__2cWMSJoP9cqN4yIK0ILkQaQ nameBuffer__persist95demo_u10;
N_LIB_PRIVATE NI32 counter__persist95demo_u11 = ((NI32)0);
N_LIB_PRIVATE tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* pebbleWindow__persist95demo_u102;
extern NIM_BOOL nimInErrorMode__system_u3510;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3510);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, rootLayer__OOZOOZOOZsrcZnebbleZwindow_u39)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0) {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* result;
	result = window_get_root_layer(window_p0);
	return result;
}
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, bounds__OOZOOZOOZsrcZnebbleZlayer_u52)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* layer_p0) {
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw result;
	result = layer_get_bounds(layer_p0);
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___system_u6018)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	return result;
}
static N_INLINE(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*, newTextLayer__OOZOOZOOZsrcZnebbleZtext95layer_u2)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0, NCSTRING text_p1, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* font_p2, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA align_p3) {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* result;
	result = text_layer_create(frame_p0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq___system_u6018(text_p1, ((NCSTRING) NIM_NIL));
		if (!!(T3_)) goto LA4_;
		text_layer_set_text(result, text_p1);
	}
LA4_: ;
	{
		if (!!((font_p2 == ((tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*) NIM_NIL)))) goto LA8_;
		text_layer_set_font(result, font_p2);
	}
LA8_: ;
	text_layer_set_text_alignment(result, align_p3);
	return result;
}
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3) {
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw));
	result.origin.x = x_p0;
	result.origin.y = y_p1;
	result.size.w = w_p2;
	result.size.h = h_p3;
	return result;
}
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZtext95layer_u33)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, NCSTRING text_p1) {
	text_layer_set_text(textLayer_p0, text_p1);
}
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZtext95layer_u42)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA alignment_p1) {
	text_layer_set_text_alignment(textLayer_p0, alignment_p1);
}
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZtext95layer_u39)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* font_p1) {
	text_layer_set_font(textLayer_p0, font_p1);
}
static N_INLINE(tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*, getSystemFont__OOZOOZOOZsrcZnebbleZfonts_u2)(NCSTRING fontKey_p0) {
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* result;
	result = fonts_get_system_font(fontKey_p0);
	return result;
}
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZtext95layer_u45)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1) {
	text_layer_set_background_color(textLayer_p0, color_p1);
}
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	(*Result).argb = argb_p0;
}
static N_INLINE(void, addChild__OOZOOZOOZsrcZnebbleZlayer_u11)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* child_p1) {
	layer_add_child(parent_p0, child_p1);
}
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, getLayer__OOZOOZOOZsrcZnebbleZtext95layer_u30)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0) {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* result;
	result = text_layer_get_layer(textLayer_p0);
	return result;
}
static N_INLINE(NIM_BOOL, exists__OOZOOZOOZsrcZnebbleZstorage_u2)(NU32 key_p0) {
	NIM_BOOL result;
	result = persist_exists(key_p0);
	return result;
}
static N_INLINE(NI32, readInt__OOZOOZOOZsrcZnebbleZstorage_u11)(NU32 key_p0) {
	NI32 result;
	result = persist_read_int(key_p0);
	return result;
}
static N_INLINE(int, readString__OOZOOZOOZsrcZnebbleZstorage_u19)(NU32 key_p0, NCSTRING buffer_p1, size_t bufferSize_p2) {
	int result;
	result = persist_read_string(key_p0, buffer_p1, bufferSize_p2);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, loadData__persist95demo_u50)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		NI32 T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = exists__OOZOOZOOZsrcZnebbleZstorage_u2(((NU32)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = (NI32)0;
		T6_ = readInt__OOZOOZOOZsrcZnebbleZstorage_u11(((NU32)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		counter__persist95demo_u11 = T6_;
	}
	goto LA1_;
LA4_: ;
	{
		counter__persist95demo_u11 = ((NI32)0);
	}
LA1_: ;
	{
		NIM_BOOL T10_;
		int T13_;
		T10_ = (NIM_BOOL)0;
		T10_ = exists__OOZOOZOOZsrcZnebbleZstorage_u2(((NU32)2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T10_) goto LA11_;
		T13_ = (int)0;
		T13_ = readString__OOZOOZOOZsrcZnebbleZstorage_u19(((NU32)2), ((NCSTRING) ((&nameBuffer__persist95demo_u10[(((NI)0))- 0]))), ((size_t)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T13_);
	}
	goto LA8_;
LA11_: ;
	{
		NimStringV2 defaultName_1;
		defaultName_1.len = 0; defaultName_1.p = NIM_NIL;
		defaultName_1 = TM__lqeHtcRlDduU9aPt9aAEw6Dw_3;
		{
			NI i_1;
			NI colontmp_;
			NI i_2;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = defaultName_1.len;
			i_2 = ((NI)0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA17;
					i_1 = i_2;
					nameBuffer__persist95demo_u10[(i_1)- 0] = defaultName_1.p->data[i_1];
					i_2 += ((NI)1);
				} LA17: ;
			}
		}
		nameBuffer__persist95demo_u10[(defaultName_1.len)- 0] = 0;
	}
LA8_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, updateDisplay__persist95demo_u12)(void) {
	NimStringV2 srcX60gensym0__1;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
	NI maxLenX60gensym0__1;
	NI copyLenX60gensym0__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	srcX60gensym0__1.len = 0; srcX60gensym0__1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = dollar___systemZdollars_u29(counter__persist95demo_u11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 9);
appendString((&T1_), TM__lqeHtcRlDduU9aPt9aAEw6Dw_5);
appendString((&T1_), colontmpD_);
	srcX60gensym0__1 = T1_;
	maxLenX60gensym0__1 = ((NI)31);
	copyLenX60gensym0__1 = ((srcX60gensym0__1.len <= maxLenX60gensym0__1) ? srcX60gensym0__1.len : maxLenX60gensym0__1);
	{
		NI iX60gensym0__1;
		NI i_1;
		iX60gensym0__1 = (NI)0;
		i_1 = ((NI)0);
		{
			while (1) {
				if (!(i_1 < copyLenX60gensym0__1)) goto LA4;
				iX60gensym0__1 = i_1;
				counterBuffer__persist95demo_u9[(iX60gensym0__1)- 0] = srcX60gensym0__1.p->data[iX60gensym0__1];
				i_1 += ((NI)1);
			} LA4: ;
		}
	}
	counterBuffer__persist95demo_u9[(copyLenX60gensym0__1)- 0] = 0;
	text_layer_set_text(counterLayer__persist95demo_u7, ((NCSTRING) ((&counterBuffer__persist95demo_u9[(((NI)0))- 0]))));
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	if (srcX60gensym0__1.p && !(srcX60gensym0__1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(srcX60gensym0__1.p);
}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, windowLoad__persist95demo_u93)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0) {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* rootLayer_1;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw bounds_1;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* titleLayer_1;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T1_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T2_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T3_;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T4_;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T5_;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T6_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T7_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T8_;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T9_;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T10_;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T11_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T12_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T13_;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T14_;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* instrLayer_1;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T15_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T16_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T17_;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T18_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	rootLayer_1 = rootLayer__OOZOOZOOZsrcZnebbleZwindow_u39(win_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	bounds_1 = bounds__OOZOOZOOZsrcZnebbleZlayer_u52(rootLayer_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)20), bounds_1.size.w, ((NI16)30));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	titleLayer_1 = newTextLayer__OOZOOZOOZsrcZnebbleZtext95layer_u2(T1_, ((NCSTRING) NIM_NIL), ((tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*) NIM_NIL), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZtext95layer_u33(titleLayer_1, "Persist Demo");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZtext95layer_u42(titleLayer_1, ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T2_ = getSystemFont__OOZOOZOOZsrcZnebbleZfonts_u2("RESOURCE_ID_GOTHIC_24_BOLD");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fonteq___OOZOOZOOZsrcZnebbleZtext95layer_u39(titleLayer_1, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T3_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T3_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZtext95layer_u45(titleLayer_1, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T4_ = getLayer__OOZOOZOOZsrcZnebbleZtext95layer_u30(titleLayer_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addChild__OOZOOZOOZsrcZnebbleZlayer_u11(rootLayer_1, T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T5_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)55), bounds_1.size.w, ((NI16)25));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T6_ = newTextLayer__OOZOOZOOZsrcZnebbleZtext95layer_u2(T5_, ((NCSTRING) NIM_NIL), ((tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*) NIM_NIL), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nameLayer__persist95demo_u8 = T6_;
	texteq___OOZOOZOOZsrcZnebbleZtext95layer_u33(nameLayer__persist95demo_u8, ((NCSTRING) ((&nameBuffer__persist95demo_u10[(((NI)0))- 0]))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZtext95layer_u42(nameLayer__persist95demo_u8, ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T7_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T7_ = getSystemFont__OOZOOZOOZsrcZnebbleZfonts_u2("RESOURCE_ID_GOTHIC_18");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fonteq___OOZOOZOOZsrcZnebbleZtext95layer_u39(nameLayer__persist95demo_u8, T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T8_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T8_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZtext95layer_u45(nameLayer__persist95demo_u8, T8_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T9_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T9_ = getLayer__OOZOOZOOZsrcZnebbleZtext95layer_u30(nameLayer__persist95demo_u8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addChild__OOZOOZOOZsrcZnebbleZlayer_u11(rootLayer_1, T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T10_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)85), bounds_1.size.w, ((NI16)35));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T11_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T11_ = newTextLayer__OOZOOZOOZsrcZnebbleZtext95layer_u2(T10_, ((NCSTRING) NIM_NIL), ((tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*) NIM_NIL), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	counterLayer__persist95demo_u7 = T11_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZtext95layer_u42(counterLayer__persist95demo_u7, ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T12_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T12_ = getSystemFont__OOZOOZOOZsrcZnebbleZfonts_u2("RESOURCE_ID_GOTHIC_28_BOLD");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fonteq___OOZOOZOOZsrcZnebbleZtext95layer_u39(counterLayer__persist95demo_u7, T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T13_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T13_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZtext95layer_u45(counterLayer__persist95demo_u7, T13_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T14_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T14_ = getLayer__OOZOOZOOZsrcZnebbleZtext95layer_u30(counterLayer__persist95demo_u7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addChild__OOZOOZOOZsrcZnebbleZlayer_u11(rootLayer_1, T14_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T15_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)125), bounds_1.size.w, ((NI16)40));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	instrLayer_1 = newTextLayer__OOZOOZOOZsrcZnebbleZtext95layer_u2(T15_, ((NCSTRING) NIM_NIL), ((tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*) NIM_NIL), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZtext95layer_u33(instrLayer_1, "SELECT: +1\012UP: +10\012DOWN: Reset");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZtext95layer_u42(instrLayer_1, ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T16_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T16_ = getSystemFont__OOZOOZOOZsrcZnebbleZfonts_u2("RESOURCE_ID_GOTHIC_14");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fonteq___OOZOOZOOZsrcZnebbleZtext95layer_u39(instrLayer_1, T16_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T17_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T17_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZtext95layer_u45(instrLayer_1, T17_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T18_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T18_ = getLayer__OOZOOZOOZsrcZnebbleZtext95layer_u30(instrLayer_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addChild__OOZOOZOOZsrcZnebbleZlayer_u11(rootLayer_1, T18_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadData__persist95demo_u50();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u12();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, destroy__OOZOOZOOZsrcZnebbleZtext95layer_u28)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* textLayer_p0) {
	text_layer_destroy(textLayer_p0);
}
N_LIB_PRIVATE N_CDECL(void, windowUnload__persist95demo_u99)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* win_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	destroy__OOZOOZOOZsrcZnebbleZtext95layer_u28(counterLayer__persist95demo_u7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	destroy__OOZOOZOOZsrcZnebbleZtext95layer_u28(nameLayer__persist95demo_u8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, onClick__OOZOOZOOZsrcZnebbleZclicks_u2)(tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q buttonId_p0, tyProc__LCJy9bQFEE8ObaRc29a4n3LA handler_p1) {
	window_single_click_subscribe(buttonId_p0, handler_p1);
}
static N_INLINE(NI32, writeInt__OOZOOZOOZsrcZnebbleZstorage_u28)(NU32 key_p0, NI32 value_p1) {
	NI32 result;
	result = persist_write_int(key_p0, value_p1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, saveData__persist95demo_u49)(void) {
	NI32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NI32)0;
	T1_ = writeInt__OOZOOZOOZsrcZnebbleZstorage_u28(((NU32)1), counter__persist95demo_u11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T1_);
	}BeforeRet_: ;
}
static N_INLINE(void, shortPulse__OOZOOZOOZsrcZnebbleZvibes_u3)(void) {
	vibes_short_pulse();
}
N_LIB_PRIVATE N_CDECL(void, selectClickHandler__persist95demo_u73)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__persist95demo_u11 += ((NI)1);
	saveData__persist95demo_u49();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u12();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!((NI32)(counter__persist95demo_u11 % ((NI32)10)) == ((NI32)0))) goto LA3_;
		shortPulse__OOZOOZOOZsrcZnebbleZvibes_u3();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, upClickHandler__persist95demo_u81)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__persist95demo_u11 += ((NI32)10);
	saveData__persist95demo_u49();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u12();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, doublePulse__OOZOOZOOZsrcZnebbleZvibes_u5)(void) {
	vibes_double_pulse();
}
N_LIB_PRIVATE N_CDECL(void, downClickHandler__persist95demo_u88)(void* recognizer_p0, void* context_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	counter__persist95demo_u11 = ((NI32)0);
	saveData__persist95demo_u49();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	updateDisplay__persist95demo_u12();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	doublePulse__OOZOOZOOZsrcZnebbleZvibes_u5();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, clickConfigProvider__persist95demo_u91)(void* context_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	onClick__OOZOOZOOZsrcZnebbleZclicks_u2(((tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q)2), selectClickHandler__persist95demo_u73);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	onClick__OOZOOZOOZsrcZnebbleZclicks_u2(((tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q)1), upClickHandler__persist95demo_u81);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	onClick__OOZOOZOOZsrcZnebbleZclicks_u2(((tyEnum_enum_ButtonId570425836__WRdsyN5X54A09bBtIGHbj1Q)3), downClickHandler__persist95demo_u88);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, init__persist95demo_u103)(void) {
	tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q T1_;
	pebbleWindow__persist95demo_u102 = window_create();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q));
	T1_.load = windowLoad__persist95demo_u93;
	T1_.unload = windowUnload__persist95demo_u99;
	window_set_window_handlers(pebbleWindow__persist95demo_u102, T1_);
	window_set_click_config_provider(pebbleWindow__persist95demo_u102, clickConfigProvider__persist95demo_u91);
	window_stack_push(pebbleWindow__persist95demo_u102, NIM_TRUE);
}
static N_INLINE(void, eventLoop__OOZOOZOOZsrcZnebbleZapp_u3)(void) {
	app_event_loop();
}
N_LIB_PRIVATE N_NIMCALL(void, deinitApp__persist95demo_u101)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	saveData__persist95demo_u49();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, deinit__persist95demo_u104)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	deinitApp__persist95demo_u101();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	window_destroy(pebbleWindow__persist95demo_u102);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(int, main)(void) {
	int result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (int)0;
	init__persist95demo_u103();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eventLoop__OOZOOZOOZsrcZnebbleZapp_u3();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	deinit__persist95demo_u104();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((int)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, NimDestroyGlobals)(void) {
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

