/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg;
typedef struct tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ;
typedef struct tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg;
typedef struct tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w;
typedef struct tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg;
typedef NU8 tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ;
struct tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg {
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* pRaw;
	tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ ownership;
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* pParent;
};
struct tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ {
	char dummy;
};
struct tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w {
	NI16 x;
	NI16 y;
};
struct tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg {
	NI16 w;
	NI16 h;
};
struct tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg {
	tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w origin;
	tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg size;
};
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZlayer_u7)(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg* h_p0);
N_CDECL(void, layer_destroy)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* layer_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg, newLayerHandle__OOZOOZOOZsrcZnebbleZuiZlayer_u87)(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg frame_p0);
static N_INLINE(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg, wrapOwned__OOZOOZOOZsrcZnebbleZuiZlayer_u68)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* p_p0);
N_CDECL(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*, layer_create)(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg frame_p0);
extern NIM_BOOL nimInErrorMode__system_u3510;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZlayer_u7)(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg* h_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*h_p0).pRaw == ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((*h_p0).ownership == ((tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ)1));
LA4_: ;
		if (!T3_) goto LA5_;
		layer_destroy((*h_p0).pRaw);
	}
LA5_: ;
	(*h_p0).pRaw = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
	(*h_p0).ownership = ((tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ)0);
	(*h_p0).pParent = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3510);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZlayer_u39)(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg* dest_p0, tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg src_p1) {
	tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg* srcPtr_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZlayer_u7(dest_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*dest_p0).pRaw = src_p1.pRaw;
	(*dest_p0).ownership = src_p1.ownership;
	(*dest_p0).pParent = src_p1.pParent;
	srcPtr_1 = ((tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg*) ((&src_p1)));
	(*srcPtr_1).pRaw = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
	(*srcPtr_1).ownership = ((tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ)0);
	(*srcPtr_1).pParent = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg, wrapOwned__OOZOOZOOZsrcZnebbleZuiZlayer_u68)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* p_p0) {
	tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg result;
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* colontmpD_;
	colontmpD_ = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
	colontmpD_ = p_p0;
	result.pRaw = colontmpD_;
	result.ownership = ((tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ)1);
	result.pParent = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg, newLayerHandle__OOZOOZOOZsrcZnebbleZuiZlayer_u87)(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg frame_p0) {
	tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg result;
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg));
	T1_ = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
	T1_ = layer_create(frame_p0);
	result = wrapOwned__OOZOOZOOZsrcZnebbleZuiZlayer_u68(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg, newLayer__OOZOOZOOZsrcZnebbleZuiZlayer_u90)(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg frame_p0) {
	tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg));
	result = newLayerHandle__OOZOOZOOZsrcZnebbleZuiZlayer_u87(frame_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
