/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A;
typedef struct tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ;
typedef struct tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA;
typedef struct tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw;
typedef struct tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A;
typedef struct tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q;
typedef struct tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg;
typedef struct tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw;
typedef struct tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg;
typedef struct tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q;
typedef union tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw;
typedef struct tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w;
typedef struct tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA;
typedef struct tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NU8 tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw;
struct tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A {
	tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* raw;
	tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw state;
};
struct tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* pRaw;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* pParent;
};
struct tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ {
	char dummy;
};
typedef N_CDECL_PTR(void, tyProc__YKpbB7RnAWujFAITf8zLgw) (tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* a0_p0);
struct tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q {
	tyProc__YKpbB7RnAWujFAITf8zLgw load;
	tyProc__YKpbB7RnAWujFAITf8zLgw appear;
	tyProc__YKpbB7RnAWujFAITf8zLgw disappear;
	tyProc__YKpbB7RnAWujFAITf8zLgw unload;
};
struct tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* pRaw;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* pParent;
};
struct tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg {
	NI16 x;
	NI16 y;
};
struct tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q {
	NI16 w;
	NI16 h;
};
struct tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw {
	tyObject_struct_GPoint570426109__MkjwgUVSXEPVhj24Lk6PGg origin;
	tyObject_struct_GSize570426113__IEdlJiAdTjfJvV1HDnqF3Q size;
};
struct tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw {
	char dummy;
};
struct tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A {
	char dummy;
};
struct tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w {
	NU8 b:2;
	NU8 g:2;
	NU8 r:2;
	NU8 a:2;
};
union tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw {
	NU8 argb;
	tyObject_union_GColor8_anon0_t__MvnUTQiGHBgaJKzoQ9aJo5w anon0;
};
typedef NI32 tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA;
typedef NI32 tyEnum_enum_TimeUnits570425923__4pNXJbcUxQEeBHr0RZT8Cw;
typedef N_CDECL_PTR(void, tyProc__7JRfVe2pz4utBaHd336Sjw) (tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw* a0_p0, tyEnum_enum_TimeUnits570425923__4pNXJbcUxQEeBHr0RZT8Cw a1_p1);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_CHAR tyArray__Wfh9bjgBQ4UqJsyISUuDSuA[16];
N_LIB_PRIVATE N_CDECL(int, main)(void);
N_NIMCALL(void, NimMain)(void);
N_LIB_PRIVATE N_CDECL(void, init__simple95watchface_u80)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* dest_p0, tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A src_p1);
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189)(void);
N_CDECL(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*, window_create)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0);
static N_INLINE(void, setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u264)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyProc__YKpbB7RnAWujFAITf8zLgw load_p1, tyProc__YKpbB7RnAWujFAITf8zLgw unload_p2, tyProc__YKpbB7RnAWujFAITf8zLgw appear_p3, tyProc__YKpbB7RnAWujFAITf8zLgw disappear_p4);
N_CDECL(void, window_set_window_handlers)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q handlers_p1);
N_LIB_PRIVATE N_CDECL(void, windowLoad__simple95watchface_u67)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* winX60gensym20__p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u53)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* destX60gensym0__p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA srcX60gensym0__p1);
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u110)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0);
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayerHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u107)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0);
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, toHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u79)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* pX60gensym0__p0);
N_CDECL(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*, text_layer_create)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0);
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3);
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, bounds__OOZOOZOOZsrcZnebbleZuiZlayer_u135)(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg h_p0);
N_CDECL(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, layer_get_bounds)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* layer_p0);
static N_INLINE(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg, toHandle__OOZOOZOOZsrcZnebbleZuiZlayer_u44)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* p_p0);
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A h_p0);
N_CDECL(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, window_get_root_layer)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u22)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* hX60gensym0__p0);
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u147)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw value_p1);
N_CDECL(void, text_layer_set_background_color)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*, toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u73)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA hX60gensym0__p0);
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw* Result);
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u138)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* value_p1);
N_CDECL(void, text_layer_set_font)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* font_p1);
N_CDECL(tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*, fonts_get_system_font)(NCSTRING font_key_p0);
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u132)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, NCSTRING value_p1);
N_CDECL(void, text_layer_set_text)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, NCSTRING text_p1);
static N_INLINE(void, textColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u144)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw value_p1);
N_CDECL(void, text_layer_set_text_color)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1);
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u141)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA value_p1);
N_CDECL(void, text_layer_set_text_alignment)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* text_layer_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA text_alignment_p1);
static N_INLINE(void, addChild__simple95watchface_u69)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* child_p1);
N_CDECL(void, layer_add_child)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* child_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, toLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u76)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA hX60gensym0__p0);
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZwindow_u252)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1);
N_CDECL(void, window_set_background_color)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw background_color_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZlayer_u6)(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg* h_p0);
N_LIB_PRIVATE N_CDECL(void, windowUnload__simple95watchface_u73)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* winX60gensym20__p0);
N_CDECL(void, tick_timer_service_subscribe)(tyEnum_enum_TimeUnits570425923__4pNXJbcUxQEeBHr0RZT8Cw tick_units_p0, tyProc__7JRfVe2pz4utBaHd336Sjw handler_p1);
N_LIB_PRIVATE N_CDECL(void, updateTime__simple95watchface_u3)(tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw* tickTime_p0, tyEnum_enum_TimeUnits570425923__4pNXJbcUxQEeBHr0RZT8Cw unitsChanged_p1);
N_CDECL(void, app_log)(NU8 log_level_p0, NCSTRING src_filename_p1, int src_line_number_p2, NCSTRING fmt_p3, ...);
static N_INLINE(NIM_BOOL, clockIs24hStyle__OOZOOZOOZsrcZnebbleZfoundationZtime_u23)(void);
N_CDECL(NIM_BOOL, clock_is_24h_style)(void);
static N_INLINE(size_t, strftime__OOZOOZOOZsrcZnebbleZfoundationZtime_u32)(NCSTRING s_p0, size_t max_p1, NCSTRING format_p2, tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw* tm_p3);
N_CDECL(int, strftime)(NCSTRING s_p0, size_t maxsize_p1, NCSTRING format_p2, tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw* tm_p_p3);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(void, push__OOZOOZOOZsrcZnebbleZuiZwindow_u199)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, NIM_BOOL animated_p1);
N_CDECL(void, window_stack_push)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* window_p0, NIM_BOOL animated_p1);
N_CDECL(void, app_event_loop)(void);
N_LIB_PRIVATE N_CDECL(void, deinit__simple95watchface_u101)(void);
N_CDECL(void, tick_timer_service_unsubscribe)(void);
static N_INLINE(NIM_BOOL, pop__OOZOOZOOZsrcZnebbleZuiZwindow_u202)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0);
N_CDECL(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*, window_stack_get_top_window)(void);
N_CDECL(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*, window_stack_pop)(NIM_BOOL animated_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, toHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u73)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* p_p0);
N_LIB_PRIVATE N_CDECL(void, _exit)(int codeX60gensym20__p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__iqQ9a0dWtOfepSow6tEbUqQ_2 = { 5 | NIM_STRLIT_FLAG, "%H:%M" };
static const NimStringV2 TM__iqQ9a0dWtOfepSow6tEbUqQ_3 = {5, (NimStrPayload*)&TM__iqQ9a0dWtOfepSow6tEbUqQ_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__iqQ9a0dWtOfepSow6tEbUqQ_4 = { 5 | NIM_STRLIT_FLAG, "%I:%M" };
static const NimStringV2 TM__iqQ9a0dWtOfepSow6tEbUqQ_5 = {5, (NimStrPayload*)&TM__iqQ9a0dWtOfepSow6tEbUqQ_4};
N_LIB_PRIVATE tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A pebbleWindow__simple95watchface_u65;
N_LIB_PRIVATE tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA timeLayer__simple95watchface_u66;
extern NIM_BOOL nimInErrorMode__system_u3510;
N_LIB_PRIVATE tyArray__Wfh9bjgBQ4UqJsyISUuDSuA timeBuffer__simple95watchface_u107;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3510);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A result;
	nimZeroMem((void*)(&result), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
	result.raw = window_create();
	result.state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)0);
	return result;
}
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
	result = newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u264)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyProc__YKpbB7RnAWujFAITf8zLgw load_p1, tyProc__YKpbB7RnAWujFAITf8zLgw unload_p2, tyProc__YKpbB7RnAWujFAITf8zLgw appear_p3, tyProc__YKpbB7RnAWujFAITf8zLgw disappear_p4) {
	tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q handlers_1;
	nimZeroMem((void*)(&handlers_1), sizeof(tyObject_struct_WindowHandlers570426229__02qYYCHBEISZffJIuzUt4Q));
	{
		if (!!((load_p1 == NIM_NIL))) goto LA3_;
		handlers_1.load = load_p1;
	}
LA3_: ;
	{
		if (!!((unload_p2 == NIM_NIL))) goto LA7_;
		handlers_1.unload = unload_p2;
	}
LA7_: ;
	{
		if (!!((appear_p3 == NIM_NIL))) goto LA11_;
		handlers_1.appear = appear_p3;
	}
LA11_: ;
	{
		if (!!((disappear_p4 == NIM_NIL))) goto LA15_;
		handlers_1.disappear = disappear_p4;
	}
LA15_: ;
	window_set_window_handlers((*h_p0).raw, handlers_1);
}
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, toHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u79)(tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* pX60gensym0__p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA result;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* colontmpD_;
	colontmpD_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	colontmpD_ = pX60gensym0__p0;
	result.pRaw = colontmpD_;
	result.pParent = ((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL);
	return result;
}
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayerHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u107)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA result;
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	T1_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T1_ = text_layer_create(frame_p0);
	result = toHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u79(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u110)(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw frame_p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	result = newTextLayerHandle__OOZOOZOOZsrcZnebbleZuiZtext95layer_u107(frame_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3) {
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw));
	result.origin.x = x_p0;
	result.origin.y = y_p1;
	result.size.w = w_p2;
	result.size.h = h_p3;
	return result;
}
static N_INLINE(tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw, bounds__OOZOOZOOZsrcZnebbleZuiZlayer_u135)(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg h_p0) {
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw result;
	result = layer_get_bounds(h_p0.pRaw);
	return result;
}
static N_INLINE(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg, toHandle__OOZOOZOOZsrcZnebbleZuiZlayer_u44)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* p_p0) {
	tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg result;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* colontmpD_;
	colontmpD_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	colontmpD_ = p_p0;
	result.pRaw = colontmpD_;
	result.pParent = ((tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*) NIM_NIL);
	return result;
}
static N_INLINE(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*, rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A h_p0) {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* result;
	result = window_get_root_layer(h_p0.raw);
	return result;
}
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u147)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw value_p1) {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T1_ = toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u73((*h_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	text_layer_set_background_color(T1_, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	(*Result).argb = argb_p0;
}
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u138)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* value_p1) {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T1_ = toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u73((*h_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	text_layer_set_font(T1_, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u132)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, NCSTRING value_p1) {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T1_ = toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u73((*h_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	text_layer_set_text(T1_, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, textColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u144)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw value_p1) {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T1_ = toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u73((*h_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	text_layer_set_text_color(T1_, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u141)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA value_p1) {
	tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (tyObject_struct_TextLayer__W2RZgVo7iB0lIlJ4pj15Iw*)0;
	T1_ = toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u73((*h_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	text_layer_set_text_alignment(T1_, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, addChild__simple95watchface_u69)(tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* parent_p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* child_p1) {
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T1_ = toLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u76((*child_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	layer_add_child(parent_p0, T1_);
	}BeforeRet_: ;
}
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZwindow_u252)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw color_p1) {
	window_set_background_color((*h_p0).raw, color_p1);
}
N_LIB_PRIVATE N_CDECL(void, windowLoad__simple95watchface_u67)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* winX60gensym20__p0) {
	tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg colontmpD_;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T1_;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T2_;
	tyObject_struct_GRect570426117__1cvu9aouLOT7LTuhbj2kIUw T3_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T4_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T5_;
	tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA* T6_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T7_;
	tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A* T8_;
	tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_LayerHandle__NN69aSAV0OqrWPtjZ0uORDg));
	T1_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T1_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230(pebbleWindow__simple95watchface_u65);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD_ = toHandle__OOZOOZOOZsrcZnebbleZuiZlayer_u44(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = bounds__OOZOOZOOZsrcZnebbleZuiZlayer_u135(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T3_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)52), T2_.size.w, ((NI16)50));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u110(T3_);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u22(&T4_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u53((&timeLayer__simple95watchface_u66), T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T5_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T5_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u147((&timeLayer__simple95watchface_u66), T5_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = (tyObject_struct_FontInfo__nTqpQAiJJxk8kM9bFrHFwHA*)0;
	T6_ = fonts_get_system_font("RESOURCE_ID_BITHAM_42_BOLD");
	fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u138((&timeLayer__simple95watchface_u66), T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u132((&timeLayer__simple95watchface_u66), "00:00");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T7_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)255), (&T7_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u144((&timeLayer__simple95watchface_u66), T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u141((&timeLayer__simple95watchface_u66), ((tyEnum_enum_GTextAlignment570426187__738WkvryWkSwnjJJREpJEA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (tyObject_struct_Layer__ArRLSoHcgGa9cBzSS1Rec1A*)0;
	T8_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u230(pebbleWindow__simple95watchface_u65);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addChild__simple95watchface_u69(T8_, (&timeLayer__simple95watchface_u66));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T9_), sizeof(tyObject_union_GColor8570426103__z6bg1Y39bpd9cp1dPIdYmWhw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)192), (&T9_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZwindow_u252((&pebbleWindow__simple95watchface_u65), T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZlayer_u6((&colontmpD_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, windowUnload__simple95watchface_u73)(tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* winX60gensym20__p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u53((&timeLayer__simple95watchface_u66), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, clockIs24hStyle__OOZOOZOOZsrcZnebbleZfoundationZtime_u23)(void) {
	NIM_BOOL result;
	result = clock_is_24h_style();
	return result;
}
static N_INLINE(size_t, strftime__OOZOOZOOZsrcZnebbleZfoundationZtime_u32)(NCSTRING s_p0, size_t max_p1, NCSTRING format_p2, tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw* tm_p3) {
	size_t result;
	int T1_;
	T1_ = (int)0;
	T1_ = strftime(s_p0, max_p1, format_p2, tm_p3);
	result = ((size_t) (T1_));
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, updateTime__simple95watchface_u3)(tyObject_struct_tm570425834__f4HhQmQy1i7MCM4hugzwaw* tickTime_p0, tyEnum_enum_TimeUnits570425923__4pNXJbcUxQEeBHr0RZT8Cw unitsChanged_p1) {
	NimStringV2 timeFmt_1;
	NimStringV2 T1_;
	size_t T8_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	timeFmt_1.len = 0; timeFmt_1.p = NIM_NIL;
	app_log(((NU8)100), "/Users/zawa/Projects/pebble/nebble/examples/simple_watchface/src/simple_watchface.nim", ((int)37), "updateTime called");
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = clockIs24hStyle__OOZOOZOOZsrcZnebbleZfoundationZtime_u23();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T4_) goto LA5_;
		timeFmt_1 = TM__iqQ9a0dWtOfepSow6tEbUqQ_3;
	}
	goto LA2_;
LA5_: ;
	{
		timeFmt_1 = TM__iqQ9a0dWtOfepSow6tEbUqQ_5;
	}
LA2_: ;
	T8_ = (size_t)0;
	T8_ = strftime__OOZOOZOOZsrcZnebbleZfoundationZtime_u32(((NCSTRING) ((&timeBuffer__simple95watchface_u107[(((NI)0))- 0]))), ((size_t)16), nimToCStringConv(timeFmt_1), tickTime_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T8_);
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u132((&timeLayer__simple95watchface_u66), ((NCSTRING) ((&timeBuffer__simple95watchface_u107[(((NI)0))- 0]))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, push__OOZOOZOOZsrcZnebbleZuiZwindow_u199)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, NIM_BOOL animated_p1) {
	window_stack_push((*h_p0).raw, animated_p1);
	(*h_p0).state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)1);
}
N_LIB_PRIVATE N_CDECL(void, init__simple95watchface_u80)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7(&T1_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50((&pebbleWindow__simple95watchface_u65), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u264((&pebbleWindow__simple95watchface_u65), windowLoad__simple95watchface_u67, windowUnload__simple95watchface_u73, NIM_NIL, NIM_NIL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	tick_timer_service_subscribe(((tyEnum_enum_TimeUnits570425923__4pNXJbcUxQEeBHr0RZT8Cw)2), updateTime__simple95watchface_u3);
	app_log(((NU8)100), "/Users/zawa/Projects/pebble/nebble/examples/simple_watchface/src/simple_watchface.nim", ((int)31), "Watchface Init");
	push__OOZOOZOOZsrcZnebbleZuiZwindow_u199((&pebbleWindow__simple95watchface_u65), NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, pop__OOZOOZOOZsrcZnebbleZuiZwindow_u202)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0) {
	NIM_BOOL result;
{	{
		tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* topWindow_1;
		if (!((*h_p0).state == ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)1))) goto LA3_;
		topWindow_1 = window_stack_get_top_window();
		{
			tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ* popped_1;
			if (!(topWindow_1 == (*h_p0).raw)) goto LA7_;
			popped_1 = window_stack_pop(NIM_TRUE);
			{
				if (!(popped_1 == (*h_p0).raw)) goto LA11_;
				(*h_p0).state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)2);
				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA11_: ;
		}
		goto LA5_;
LA7_: ;
		{
		}
LA5_: ;
	}
LA3_: ;
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, deinit__simple95watchface_u101)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	tick_timer_service_unsubscribe();
	{
		NIM_BOOL T3_;
		tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = pop__OOZOOZOOZsrcZnebbleZuiZwindow_u202((&pebbleWindow__simple95watchface_u65));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = toHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u73(((tyObject_struct_Window__esLx3vYHW9aoDk9a25tQZ3QQ*) NIM_NIL));
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7(&T6_); goto BeforeRet_;}
		eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50((&pebbleWindow__simple95watchface_u65), T6_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(int, main)(void) {
	int result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (int)0;
	NimMain();
	init__simple95watchface_u80();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	app_event_loop();
	deinit__simple95watchface_u101();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((int)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, _exit)(int codeX60gensym20__p0) {
}
N_LIB_PRIVATE N_CDECL(void, NimDestroyGlobals)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u22((&timeLayer__simple95watchface_u66));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7((&pebbleWindow__simple95watchface_u65));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

