/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A;
typedef struct tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA;
typedef struct tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA;
typedef struct tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ;
typedef struct tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ;
typedef struct tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ;
typedef struct tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg;
typedef struct tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w;
typedef struct tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg;
typedef union tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw;
typedef struct tyObject_union_GColor8_anon0_t__CMihq5cObL5TRHT7QyD9bEA tyObject_union_GColor8_anon0_t__CMihq5cObL5TRHT7QyD9bEA;
typedef struct tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng;
typedef struct tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NU8 tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw;
struct tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A {
	tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* raw;
	tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw state;
};
typedef NU8 tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ;
struct tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA {
	tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* pRaw;
	tyEnum_HandleOwnership__3LuuM4we4wvfaiVTiUX3UQ ownership;
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* pParent;
};
struct tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA {
	char dummy;
};
typedef N_CDECL_PTR(void, tyProc__AL9bRLkzEO68chD0gurqcTA) (tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* a0_p0);
struct tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ {
	tyProc__AL9bRLkzEO68chD0gurqcTA load;
	tyProc__AL9bRLkzEO68chD0gurqcTA appear;
	tyProc__AL9bRLkzEO68chD0gurqcTA disappear;
	tyProc__AL9bRLkzEO68chD0gurqcTA unload;
};
struct tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w {
	NI16 x;
	NI16 y;
};
struct tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg {
	NI16 w;
	NI16 h;
};
struct tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg {
	tyObject_struct_GPoint570426121__3IzUVdS3RabK9beblMHZu3w origin;
	tyObject_struct_GSize570426125__qlPUtl57k7rFH3URuNaRBg size;
};
struct tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ {
	char dummy;
};
struct tyObject_union_GColor8_anon0_t__CMihq5cObL5TRHT7QyD9bEA {
	NU8 b:2;
	NU8 g:2;
	NU8 r:2;
	NU8 a:2;
};
union tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw {
	NU8 argb;
	tyObject_union_GColor8_anon0_t__CMihq5cObL5TRHT7QyD9bEA anon0;
};
typedef NI32 tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA;
typedef NI32 tyEnum_enum_TimeUnits570425935__BAIvMj9aVtohKpd8SeDllQQ;
typedef N_CDECL_PTR(void, tyProc__UuDofshMTnGz4z49abhwoEg) (tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w* a0_p0, tyEnum_enum_TimeUnits570425935__BAIvMj9aVtohKpd8SeDllQQ a1_p1);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_CHAR tyArray__Wfh9bjgBQ4UqJsyISUuDSuA[16];
N_LIB_PRIVATE N_CDECL(int, main)(void);
N_NIMCALL(void, NimMain)(void);
N_LIB_PRIVATE N_CDECL(void, init__simple95watchface_u98)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* dest_p0, tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A src_p1);
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189)(void);
N_CDECL(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*, window_create)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0);
static N_INLINE(void, setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u307)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyProc__AL9bRLkzEO68chD0gurqcTA load_p1, tyProc__AL9bRLkzEO68chD0gurqcTA unload_p2, tyProc__AL9bRLkzEO68chD0gurqcTA appear_p3, tyProc__AL9bRLkzEO68chD0gurqcTA disappear_p4);
N_CDECL(void, window_set_window_handlers)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0, tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ handlers_p1);
N_LIB_PRIVATE N_CDECL(void, windowLoad__simple95watchface_u65)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u55)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* destX60gensym0__p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA srcX60gensym0__p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA, newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u127)(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg frame_p0);
static N_INLINE(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3);
static N_INLINE(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, bounds__OOZOOZOOZsrcZnebbleZuiZlayer_u232)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* p_p0);
N_CDECL(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, layer_get_bounds)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* layer_p0);
static N_INLINE(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*, rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u242)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0);
N_CDECL(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*, window_get_root_layer)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u24)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* hX60gensym0__p0);
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u212)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw value_p1);
N_CDECL(void, text_layer_set_background_color)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw color_p1);
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw* Result);
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u170)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng* value_p1);
N_CDECL(void, text_layer_set_font)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng* font_p1);
N_CDECL(tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng*, fonts_get_system_font)(NCSTRING font_key_p0);
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u149)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, NCSTRING value_p1);
N_CDECL(void, text_layer_set_text)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, NCSTRING text_p1);
static N_INLINE(void, textColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u198)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw value_p1);
N_CDECL(void, text_layer_set_text_color)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw color_p1);
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u184)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA value_p1);
N_CDECL(void, text_layer_set_text_alignment)(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* text_layer_p0, tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA text_alignment_p1);
static N_INLINE(void, addChild__simple95watchface_u75)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* parent_p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* child_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*, toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u75)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA hX60gensym0__p0);
N_CDECL(void, layer_add_child)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* parent_p0, tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* child_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*, toLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u78)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA hX60gensym0__p0);
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZwindow_u279)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw color_p1);
N_CDECL(void, window_set_background_color)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw background_color_p1);
N_LIB_PRIVATE N_CDECL(void, windowUnload__simple95watchface_u91)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0);
static N_INLINE(void, push__OOZOOZOOZsrcZnebbleZuiZwindow_u199)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, NIM_BOOL animated_p1);
N_CDECL(void, window_stack_push)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* window_p0, NIM_BOOL animated_p1);
N_CDECL(void, tick_timer_service_subscribe)(tyEnum_enum_TimeUnits570425935__BAIvMj9aVtohKpd8SeDllQQ tick_units_p0, tyProc__UuDofshMTnGz4z49abhwoEg handler_p1);
N_LIB_PRIVATE N_CDECL(void, updateTime__simple95watchface_u3)(tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w* tickTime_p0, tyEnum_enum_TimeUnits570425935__BAIvMj9aVtohKpd8SeDllQQ unitsChanged_p1);
N_CDECL(void, app_log)(NU8 log_level_p0, NCSTRING src_filename_p1, int src_line_number_p2, NCSTRING fmt_p3, ...);
static N_INLINE(NIM_BOOL, clockIs24hStyle__OOZOOZOOZsrcZnebbleZfoundationZtime_u23)(void);
N_CDECL(NIM_BOOL, clock_is_24h_style)(void);
static N_INLINE(size_t, strftime__OOZOOZOOZsrcZnebbleZfoundationZtime_u32)(NCSTRING s_p0, size_t max_p1, NCSTRING format_p2, tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w* tm_p3);
N_CDECL(int, strftime)(NCSTRING s_p0, size_t maxsize_p1, NCSTRING format_p2, tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w* tm_p_p3);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_CDECL(void, app_event_loop)(void);
N_LIB_PRIVATE N_CDECL(void, deinit__simple95watchface_u119)(void);
N_CDECL(void, tick_timer_service_unsubscribe)(void);
static N_INLINE(NIM_BOOL, pop__OOZOOZOOZsrcZnebbleZuiZwindow_u206)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0);
N_CDECL(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*, window_stack_get_top_window)(void);
N_CDECL(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*, window_stack_pop)(NIM_BOOL animated_p0);
N_LIB_PRIVATE N_CDECL(void, _exit)(int codeX60gensym21__p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__iqQ9a0dWtOfepSow6tEbUqQ_2 = { 5 | NIM_STRLIT_FLAG, "%H:%M" };
static const NimStringV2 TM__iqQ9a0dWtOfepSow6tEbUqQ_3 = {5, (NimStrPayload*)&TM__iqQ9a0dWtOfepSow6tEbUqQ_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__iqQ9a0dWtOfepSow6tEbUqQ_4 = { 5 | NIM_STRLIT_FLAG, "%I:%M" };
static const NimStringV2 TM__iqQ9a0dWtOfepSow6tEbUqQ_5 = {5, (NimStrPayload*)&TM__iqQ9a0dWtOfepSow6tEbUqQ_4};
N_LIB_PRIVATE tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A pebbleWindow__simple95watchface_u63;
N_LIB_PRIVATE tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA timeLayer__simple95watchface_u64;
extern NIM_BOOL nimInErrorMode__system_u3510;
N_LIB_PRIVATE tyArray__Wfh9bjgBQ4UqJsyISUuDSuA timeBuffer__simple95watchface_u130;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3510);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A result;
	nimZeroMem((void*)(&result), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
	result.raw = window_create();
	result.state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)0);
	return result;
}
static N_INLINE(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A, newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
	result = newWindowHandle__OOZOOZOOZsrcZnebbleZuiZwindow_u189();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u307)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyProc__AL9bRLkzEO68chD0gurqcTA load_p1, tyProc__AL9bRLkzEO68chD0gurqcTA unload_p2, tyProc__AL9bRLkzEO68chD0gurqcTA appear_p3, tyProc__AL9bRLkzEO68chD0gurqcTA disappear_p4) {
	tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ handlers_1;
{	{
		if (!((*h_p0).raw == ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	nimZeroMem((void*)(&handlers_1), sizeof(tyObject_struct_WindowHandlers570426241__LjZh1APfxAVIL556StHLrQ));
	{
		if (!!((load_p1 == NIM_NIL))) goto LA7_;
		handlers_1.load = load_p1;
	}
LA7_: ;
	{
		if (!!((unload_p2 == NIM_NIL))) goto LA11_;
		handlers_1.unload = unload_p2;
	}
LA11_: ;
	{
		if (!!((appear_p3 == NIM_NIL))) goto LA15_;
		handlers_1.appear = appear_p3;
	}
LA15_: ;
	{
		if (!!((disappear_p4 == NIM_NIL))) goto LA19_;
		handlers_1.disappear = disappear_p4;
	}
LA19_: ;
	window_set_window_handlers((*h_p0).raw, handlers_1);
	}BeforeRet_: ;
}
static N_INLINE(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487)(NI16 x_p0, NI16 y_p1, NI16 w_p2, NI16 h_p3) {
	tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg result;
	nimZeroMem((void*)(&result), sizeof(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg));
	result.origin.x = x_p0;
	result.origin.y = y_p1;
	result.size.w = w_p2;
	result.size.h = h_p3;
	return result;
}
static N_INLINE(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg, bounds__OOZOOZOOZsrcZnebbleZuiZlayer_u232)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* p_p0) {
	tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg result;
{	nimZeroMem((void*)(&result), sizeof(tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg));
	{
		if (!(p_p0 == ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	result = layer_get_bounds(p_p0);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*, rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u242)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0) {
	tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* result;
{	result = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
	{
		if (!(win_p0 == ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL))) goto LA3_;
		result = ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL);
		goto BeforeRet_;
	}
LA3_: ;
	result = window_get_root_layer(win_p0);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u212)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw value_p1) {
{	{
		if (!((*h_p0).pRaw == ((tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	text_layer_set_background_color((*h_p0).pRaw, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515)(NU8 argb_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw));
	(*Result).argb = argb_p0;
}
static N_INLINE(void, fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u170)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng* value_p1) {
{	{
		if (!((*h_p0).pRaw == ((tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	text_layer_set_font((*h_p0).pRaw, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u149)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, NCSTRING value_p1) {
{	{
		if (!((*h_p0).pRaw == ((tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	text_layer_set_text((*h_p0).pRaw, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, textColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u198)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw value_p1) {
{	{
		if (!((*h_p0).pRaw == ((tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	text_layer_set_text_color((*h_p0).pRaw, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u184)(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* h_p0, tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA value_p1) {
{	{
		if (!((*h_p0).pRaw == ((tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	text_layer_set_text_alignment((*h_p0).pRaw, value_p1);
	}BeforeRet_: ;
}
static N_INLINE(void, addChild__simple95watchface_u75)(tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* parent_p0, tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA* child_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ* T5_;
		tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((parent_p0 == ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T5_ = (tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*)0;
		T5_ = toPtr__OOZOOZOOZsrcZnebbleZuiZtext95layer_u75((*child_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T3_ = !((T5_ == ((tyObject_struct_TextLayer__nw9b2AOGA5VlSCdX45JcJqQ*) NIM_NIL)));
LA4_: ;
		if (!T3_) goto LA6_;
		T8_ = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
		T8_ = toLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u78((*child_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		layer_add_child(parent_p0, T8_);
	}
LA6_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZwindow_u279)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw color_p1) {
{	{
		if (!((*h_p0).raw == ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	window_set_background_color((*h_p0).raw, color_p1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, windowLoad__simple95watchface_u65)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0) {
	NI16 colontmpD_;
	NI16 colontmpD__2;
	NI16 T1_;
	tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg T11_;
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T12_;
	tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw T13_;
	tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng* T14_;
	tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw T15_;
	tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw T22_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = (NI16)0;
	colontmpD__2 = (NI16)0;
	T1_ = (NI16)0;
	{
		tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* T6_;
		tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg T7_;
		if (!!((((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL) == ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL)))) goto LA4_;
		T6_ = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
		T6_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u242(win_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T7_ = bounds__OOZOOZOOZsrcZnebbleZuiZlayer_u232(T6_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD_ = T7_.size.w;
		T1_ = colontmpD_;
	}
	goto LA2_;
LA4_: ;
	{
		tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* T9_;
		tyObject_struct_GRect570426129__ba9bjUwtvD4v9a2AKX0gWCcg T10_;
		T9_ = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
		T9_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u242(win_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T10_ = bounds__OOZOOZOOZsrcZnebbleZuiZlayer_u232(T9_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__2 = T10_.size.w;
		T1_ = colontmpD__2;
	}
LA2_: ;
	T11_ = makeGRect__OOZOOZOOZsrcZnebbleZffi_u3487(((NI16)0), ((NI16)52), T1_, ((NI16)50));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T12_ = newTextLayer__OOZOOZOOZsrcZnebbleZuiZtext95layer_u127(T11_);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u24(&T12_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u55((&timeLayer__simple95watchface_u64), T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T13_), sizeof(tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)0), (&T13_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u212((&timeLayer__simple95watchface_u64), T13_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T14_ = (tyObject_struct_FontInfo__OThMgPKJgGYHGdVfrJ27ng*)0;
	T14_ = fonts_get_system_font("RESOURCE_ID_BITHAM_42_BOLD");
	fonteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u170((&timeLayer__simple95watchface_u64), T14_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u149((&timeLayer__simple95watchface_u64), "00:00");
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T15_), sizeof(tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)255), (&T15_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textColoreq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u198((&timeLayer__simple95watchface_u64), T15_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	textAlignmenteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u184((&timeLayer__simple95watchface_u64), ((tyEnum_enum_GTextAlignment570426199__GoX9aZdlRH7BVghtSOwHTqA)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!!((((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL) == ((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL)))) goto LA18_;
		addChild__simple95watchface_u75(((tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*) NIM_NIL), (&timeLayer__simple95watchface_u64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA16_;
LA18_: ;
	{
		tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ* T21_;
		T21_ = (tyObject_struct_Layer__KCpfpF2jwj5coKARWsuAMQ*)0;
		T21_ = rootLayer__OOZOOZOOZsrcZnebbleZuiZwindow_u242(win_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		addChild__simple95watchface_u75(T21_, (&timeLayer__simple95watchface_u64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA16_: ;
	nimZeroMem((void*)(&T22_), sizeof(tyObject_union_GColor8570426115__5r6qkn4jWQz1dbWRrH9aefw));
	makeGColor8__OOZOOZOOZsrcZnebbleZffi_u3515(((NU8)192), (&T22_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backgroundColoreq___OOZOOZOOZsrcZnebbleZuiZwindow_u279((&pebbleWindow__simple95watchface_u63), T22_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, windowUnload__simple95watchface_u91)(tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* win_p0) {
	tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_TextLayerHandle__t9bAY9a7d2BLJR3FU4TDoSGA));
	eqsink___OOZOOZOOZsrcZnebbleZuiZtext95layer_u55((&timeLayer__simple95watchface_u64), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, push__OOZOOZOOZsrcZnebbleZuiZwindow_u199)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0, NIM_BOOL animated_p1) {
{	{
		if (!((*h_p0).raw == ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	window_stack_push((*h_p0).raw, animated_p1);
	(*h_p0).state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)1);
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, clockIs24hStyle__OOZOOZOOZsrcZnebbleZfoundationZtime_u23)(void) {
	NIM_BOOL result;
	result = clock_is_24h_style();
	return result;
}
static N_INLINE(size_t, strftime__OOZOOZOOZsrcZnebbleZfoundationZtime_u32)(NCSTRING s_p0, size_t max_p1, NCSTRING format_p2, tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w* tm_p3) {
	size_t result;
	int T1_;
	T1_ = (int)0;
	T1_ = strftime(s_p0, max_p1, format_p2, tm_p3);
	result = ((size_t) (T1_));
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, updateTime__simple95watchface_u3)(tyObject_struct_tm570425846__WpbcetfvPwreM3x2G9bxF3w* tickTime_p0, tyEnum_enum_TimeUnits570425935__BAIvMj9aVtohKpd8SeDllQQ unitsChanged_p1) {
	NimStringV2 timeFmt_1;
	NimStringV2 T1_;
	size_t T8_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	timeFmt_1.len = 0; timeFmt_1.p = NIM_NIL;
	app_log(((NU8)100), "/Users/zawa/Projects/pebble/nebble/examples/simple_watchface/src/simple_watchface.nim", ((int)37), "updateTime called");
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = clockIs24hStyle__OOZOOZOOZsrcZnebbleZfoundationZtime_u23();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T4_) goto LA5_;
		timeFmt_1 = TM__iqQ9a0dWtOfepSow6tEbUqQ_3;
	}
	goto LA2_;
LA5_: ;
	{
		timeFmt_1 = TM__iqQ9a0dWtOfepSow6tEbUqQ_5;
	}
LA2_: ;
	T8_ = (size_t)0;
	T8_ = strftime__OOZOOZOOZsrcZnebbleZfoundationZtime_u32(((NCSTRING) ((&timeBuffer__simple95watchface_u130[(((NI)0))- 0]))), ((size_t)16), nimToCStringConv(timeFmt_1), tickTime_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T8_);
	texteq___OOZOOZOOZsrcZnebbleZuiZtext95layer_u149((&timeLayer__simple95watchface_u64), ((NCSTRING) ((&timeBuffer__simple95watchface_u130[(((NI)0))- 0]))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, init__simple95watchface_u98)(void) {
	tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = newWindow__OOZOOZOOZsrcZnebbleZuiZwindow_u191();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7(&T1_); goto BeforeRet_;}
	eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50((&pebbleWindow__simple95watchface_u63), T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setHandlers__OOZOOZOOZsrcZnebbleZuiZwindow_u307((&pebbleWindow__simple95watchface_u63), windowLoad__simple95watchface_u65, windowUnload__simple95watchface_u91, NIM_NIL, NIM_NIL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	push__OOZOOZOOZsrcZnebbleZuiZwindow_u199((&pebbleWindow__simple95watchface_u63), NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	tick_timer_service_subscribe(((tyEnum_enum_TimeUnits570425935__BAIvMj9aVtohKpd8SeDllQQ)2), updateTime__simple95watchface_u3);
	app_log(((NU8)100), "/Users/zawa/Projects/pebble/nebble/examples/simple_watchface/src/simple_watchface.nim", ((int)31), "Watchface Init");
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, pop__OOZOOZOOZsrcZnebbleZuiZwindow_u206)(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A* h_p0) {
	NIM_BOOL result;
{	{
		if (!((*h_p0).raw == ((tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA*) NIM_NIL))) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	{
		tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* topWindow_1;
		if (!((*h_p0).state == ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)1))) goto LA7_;
		topWindow_1 = window_stack_get_top_window();
		{
			tyObject_struct_Window__x0oI0MSh79clnNFs7R9bwHcA* popped_1;
			if (!(topWindow_1 == (*h_p0).raw)) goto LA11_;
			popped_1 = window_stack_pop(NIM_TRUE);
			{
				if (!(popped_1 == (*h_p0).raw)) goto LA15_;
				(*h_p0).state = ((tyEnum_ResourceState__zuZLKhn7SRnYvk4iCTdAkw)2);
				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA15_: ;
		}
LA11_: ;
	}
LA7_: ;
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, deinit__simple95watchface_u119)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	tick_timer_service_unsubscribe();
	{
		NIM_BOOL T3_;
		tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = pop__OOZOOZOOZsrcZnebbleZuiZwindow_u206((&pebbleWindow__simple95watchface_u63));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimZeroMem((void*)(&T6_), sizeof(tyObject_WindowHandle__QyOpsx5EVgiof5UakzQL7A));
		eqsink___OOZOOZOOZsrcZnebbleZuiZwindow_u50((&pebbleWindow__simple95watchface_u63), T6_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(int, main)(void) {
	int result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (int)0;
	NimMain();
	init__simple95watchface_u98();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	app_event_loop();
	deinit__simple95watchface_u119();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((int)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, _exit)(int codeX60gensym21__p0) {
}
N_LIB_PRIVATE N_CDECL(void, NimDestroyGlobals)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZtext95layer_u24((&timeLayer__simple95watchface_u64));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZOOZOOZsrcZnebbleZuiZwindow_u7((&pebbleWindow__simple95watchface_u63));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

